= Summary

. link:admin/Administrators_Guide.adoc[Administrator's Guide]
.. link:admin/Installation_Guide.adoc[Installation Guide]
.. link:admin/Deploying_VDBs.adoc[Deploying VDBs]
... link:admin/Deploying_VDB_Dependencies.adoc[Deploying VDB Dependencies]
.... link:admin/Accumulo_Data_Sources.adoc[Accumulo Data Sources]
.... link:admin/Amazon_SimpleDB_Data_Sources.adoc[Amazon SimpleDB Data Sources]
.... link:admin/Cassandra_Data_Sources.adoc[Cassandra Data Sources]
.... link:admin/File_Data_Sources.adoc[File Data Sources]
.... link:admin/Google_Spreadsheet_Data_Sources.adoc[Google Spreadsheet Data Sources]
.... link:admin/Infinispan_Data_Sources.adoc[Infinispan Data Sources]
.... link:admin/Infinispan-DSL_Data_Sources.adoc[Infinispan-DSL Data Sources]
.... link:admin/JDBC_Data_Sources.adoc[JDBC Data Sources]
.... link:admin/LDAP_Data_Sources.adoc[LDAP Data Sources]
.... link:admin/MongoDB_Data_Sources.adoc[MongoDB Data Sources]
.... link:admin/Phoenix_Data_Sources.adoc[Phoenix Data Sources]
.... link:admin/Salesforce_Data_Sources.adoc[Salesforce Data Sources]
.... link:admin/Solr_Data_Sources.adoc[Solr Data Sources]
.... link:admin/Web_Service_Data_Sources.adoc[Web Service Data Sources]
..... link:admin/Kerberos_with_REST_based_Services.adoc[Kerberos with REST based Services]
..... link:admin/OAuth_Authentication_With_REST_Based_Services.adoc[OAuth Authentication With REST Based Services]
.... link:admin/Coherence_Data_Sources.adoc[Coherence Data Sources]
... link:admin/VDB_Versioning.adoc[VDB Versioning]
... link:admin/Migrating_VDBs_from_6.x.adoc[Migrating VDBs from 6.x]
.. link:admin/Logging.adoc[Logging]
.. link:admin/Clustering_in_Teiid.adoc[Clustering in Teiid]
.. link:admin/Monitoring.adoc[Monitoring]
.. link:admin/Performance_Tuning.adoc[Performance Tuning]
... link:admin/Memory_Management.adoc[Memory Management]
... link:admin/Threading.adoc[Threading]
... link:admin/Cache_Tuning.adoc[Cache Tuning]
... link:admin/Socket_Transports.adoc[Socket Transports]
... link:admin/LOBs.adoc[LOBs]
... link:admin/Other_Considerations.adoc[Other Considerations]
.. link:admin/Teiid_Console.adoc[Teiid Console]
.. link:admin/AdminShell.adoc[AdminShell]
... link:admin/Getting_Started.adoc[Getting Started]
... link:admin/Executing_a_script_file.adoc[Executing a script file]
... link:admin/Log_File_and_Recorded_Script_file.adoc[Log File and Recorded Script file]
... link:admin/Default_Connection_Properties.adoc[Default Connection Properties]
... link:admin/Handling_Multiple_Connections.adoc[Handling Multiple Connections]
... link:admin/Interactive_Shell_Nuances.adoc[Interactive Shell Nuances]
.. link:admin/Other_Scripting_Environments.adoc[Other Scripting Environments]
.. link:admin/System_Properties.adoc[System Properties]
.. link:admin/Teiid_Management_CLI.adoc[Teiid Management CLI]
.. link:admin/Migration_Guide_From_Teiid_8.x.adoc[Migration Guide From Teiid 8.x]

. link:caching/Caching_Guide.adoc[Caching Guide]
.. link:caching/Results_Caching.adoc[Results Caching]
.. link:caching/Materialized_Views.adoc[Materialized Views]
... link:caching/External_Materialization.adoc[External Materialization]
... link:caching/Internal_Materialization.adoc[Internal Materialization]
.. link:caching/Code_Table_Caching.adoc[Code Table Caching]
.. link:caching/Translator_Results_Caching.adoc[Translator Results Caching]
.. link:caching/Hints_and_Options.adoc[Hints and Options]
.. link:caching/Programmatic_Control.adoc[Programmatic Control]

. link:client-dev/Client_Developers_Guide.adoc[Client Developer's Guide]
.. link:client-dev/Reauthentication.adoc[Reauthentication]
.. link:client-dev/Execution_Properties.adoc[Execution Properties]
... link:client-dev/XML_extensions.adoc[XML extensions]
.. link:client-dev/SET_Statement.adoc[SET Statement]
.. link:client-dev/SHOW_Statement.adoc[SHOW Statement]
.. link:client-dev/Transactions.adoc[Transactions]
... link:client-dev/Local_Transactions.adoc[Local Transactions]
... link:client-dev/Request_Level_Transactions.adoc[Request Level Transactions]
... link:client-dev/Using_Global_Transactions.adoc[Using Global Transactions]
... link:client-dev/Restrictions.adoc[Restrictions]
.. link:client-dev/ODBC_Support.adoc[ODBC Support]
... link:client-dev/Installing_the_ODBC_Driver_Client.adoc[Installing the ODBC Driver Client]
... link:client-dev/Configuring_the_Data_Source_Name_DSN.adoc[Configuring the Data Source Name (DSN)]
... link:client-dev/DSN_Less_Connection.adoc[DSN Less Connection]
.. link:client-dev/JDBC_Support.adoc[JDBC Support]
... link:client-dev/Connecting_to_a_Teiid_Server.adoc[Connecting to a Teiid Server]
.... link:client-dev/Driver_Connection.adoc[Driver Connection]
.... link:client-dev/DataSource_Connection.adoc[DataSource Connection]
.... link:client-dev/Standalone_Application.adoc[Standalone Application]
.... link:client-dev/JBoss_AS_DataSource.adoc[JBoss AS DataSource]
.... link:client-dev/Using_Multiple_Hosts.adoc[Using Multiple Hosts]
.... link:client-dev/SSL_Client_Connections.adoc[SSL Client Connections]
.... link:client-dev/Additional_Socket_Client_Settings.adoc[Additional Socket Client Settings]
... link:client-dev/Prepared_Statements.adoc[Prepared Statements]
... link:client-dev/ResultSet_Limitations.adoc[ResultSet Limitations]
... link:client-dev/JDBC_Extensions.adoc[JDBC Extensions]
.... link:client-dev/Statement_Extensions.adoc[Statement Extensions]
.... link:client-dev/Partial_Results_Mode.adoc[Partial Results Mode]
.... link:client-dev/Non-blocking_Statement_Execution.adoc[blocking Statement Execution]
.... link:client-dev/ResultSet_Extensions.adoc[ResultSet Extensions]
.... link:client-dev/Connection_Extensions.adoc[Connection Extensions]
... link:client-dev/Unsupported_JDBC_Methods.adoc[Unsupported JDBC Methods]
.... link:client-dev/Unsupported_Classes_and_Methods_in_java.sql.adoc[Unsupported Classes and Methods in "java.sql"]
.... link:client-dev/Unsupported_Classes_and_Methods_in_javax.sql.adoc[Unsupported Classes and Methods in "javax.sql"]
.. link:client-dev/OData_Support.adoc[OData Support]
.. link:client-dev/Using_Teiid_with_Hibernate.adoc[Using Teiid with Hibernate]
.. link:client-dev/Using_Teiid_with_EclipseLink.adoc[Using Teiid with EclipseLink]

. link:dev/Developers_Guide.adoc[Developer's Guide]
.. link:dev/Developing_JEE_Connectors.adoc[Developing JEE Connectors]
... link:dev/Connector_Environment_Setup.adoc[Connector Environment Setup]
.... link:dev/Build_Environment.adoc[Build Environment]
.... link:dev/Archetype_Template_Connector_Project.adoc[Archetype Template Connector Project]
... link:dev/Implementing_the_Teiid_Framework.adoc[Implementing the Teiid Framework]
.... link:dev/ra.xml_file_Template.adoc[ra.xml file Template]
... link:dev/Packaging_the_Adapter.adoc[Packaging the Adapter]
.... link:dev/Adding_Dependent_Libraries.adoc[Adding Dependent Libraries]
... link:dev/Deploying_the_Adapter.adoc[Deploying the Adapter]
.. link:dev/Translator_Development.adoc[Translator Development]
... link:dev/Environment_Setup.adoc[Environment Setup]
.... link:dev/Setting_up_the_build_environment.adoc[Setting up the build environment]
.... link:dev/Archetype_Template_Translator_Project.adoc[Archetype Template Translator Project]
... link:dev/Implementing_the_Framework.adoc[Implementing the Framework]
.... link:dev/Caching_API.adoc[Caching API]
.... link:dev/Command_Language.adoc[Command Language]
.... link:dev/Connections_to_Source.adoc[Connections to Source]
.... link:dev/Dependent_Join_Pushdown.adoc[Dependent Join Pushdown]
.... link:dev/Executing_Commands.adoc[Executing Commands]
.... link:dev/Extending_the_ExecutionFactory_Class.adoc[Extending the ExecutionFactory Class]
.... link:dev/Large_Objects.adoc[Large Objects]
.... link:dev/Translator_Capabilities.adoc[Translator Capabilities]
.... link:dev/Translator_Properties.adoc[Translator Properties]
... link:dev/Extending_The_JDBC_Translator.adoc[Extending The JDBC Translator]
... link:dev/Delegating_Translator.adoc[Delegating Translator]
... link:dev/Packaging.adoc[Packaging]
.... link:dev/Adding_Dependent_Modules.adoc[Adding Dependent Modules]
... link:dev/Deployment.adoc[Deployment]
.. link:dev/User_Defined_Functions.adoc[User Defined Functions]
... link:dev/Source_Supported_Functions.adoc[Source Supported Functions]
... link:dev/Support_for_User-Defined_Functions_Non-Pushdown.adoc[Support for User-Defined Functions(Non-Pushdown)]
.. link:dev/AdminAPI.adoc[AdminAPI]
.. link:dev/Custom_Logging.adoc[Custom Logging]
.. link:dev/Runtime_Updates.adoc[Runtime Updates]
.. link:dev/Advanced_Topics.adoc[Advanced Topics]
.. link:dev/Custom_Metadata_Repository.adoc[Custom Metadata Repository]
.. link:dev/PreParser.adoc[PreParser]

. link:embedded/Embedded_Guide.adoc[Embedded Guide]
.. link:embedded/Logging_in_Teiid_Embedded.adoc[Logging in Teiid Embedded]
.. link:embedded/Secure_Embedded_with_PicketBox.adoc[Secure Embedded with PicketBox]

. link:security/Security_Guide.adoc[Security Guide]
.. link:security/LoginModules.adoc[LoginModules]
.. link:security/Teiid_Server_Transport_Security.adoc[Teiid Server Transport Security]
.. link:security/Generating_Self_Signed_Certificates.adoc[Generating Self Signed Certificates]
.. link:security/Data_Source_Security.adoc[Data Source Security]
.. link:security/Kerberos_support_through_GSSAPI.adoc[Kerberos support through GSSAPI]
.. link:security/Custom_Authorization_Validator.adoc[Custom Authorization Validator]
.. link:security/SAML_Based_Security_For_OData.adoc[SAML Based Security For OData]
