
= Programmatic Control

Teiid exposes a bean that implements the _org.teiid.events.EventDistributor_ interface. It can be looked up in JNDI under the name _teiid/event-distributor-factory_. The `EventDistributor` exposes methods like _dataModification_ (which affects result set caching) or _updateMatViewRow_ (which affects internal materialization) to alert the Teiid engine that the underlying source data has been modified. These operations, which work cluster wide will invalidate the cache entries appropriately and reload the new cache contents.

NOTE: *Change Data Capture* - If your source system has any built-in change data capture facilities that can scrape logs, install triggers, etc. to capture data change events, they can captured and can be propagated to Teiid engine through a pojo bean/MDB/Session Bean deployed in {{ book.asName }} engine.

The below shows a code example as how user can use `EventDistributor` interface in their own code that is deployed in the same {{ book.asName }} VM using a Pojo/MDB/Session Bean. Consult {{ book.asName }} documents deploying as bean as they out of scope for this document.


[source,java]
.*EventDistributor Code Example
----
public class ChangeDataCapture {

    public void invalidate() {
        InitialContext ic = new InitialContext();
        EventDistributor ed = ((EventDistributorFactory)ic.lookup("teiid/event-distributor-factory")).getEventDistributor();

        // this below line indicates that Customer table in the "model-name" schema has been changed.
        // this result in cache reload.
        ed.dataModification("vdb-name", "version", "model-name", "Customer");
    }
}
----

NOTE: *Updating Costing information* - The _EventDistributor_ interface also exposes many methods that can be used to update the costing information on your source models for optimized query planning. Note that these values volatile and will be lost during a cluster re-start, as there is no repository to persist.
