
= Archetype Template PreParser Project 

One way to start developing a custom preparser is to create a project using the Teiid archetype template. When the project is created from the template, it will contain an example class and resources for you to begin adding your custom logic. Additionally, the maven dependencies are defined in the pom.xml so that you can begin compiling the classes.

NOTE: The project will be created as an independent project and has no parent maven dependencies. It’s designed to be built independent of building Teiid.

You have 2 options for creating a translator project; in Eclipse by creating a new maven project from the arche type or by using the command line to generate the project.

== Create Project in Eclipse

To create a Java project in Eclipse from an arche type, perform the following:

* Open the JAVA perspective
* From the menu select File –> New —> Other
* In the tree, expand Maven and select Maven Project, press Next
* On the "Select project name and Location" window, you can accept the defaults, press Next
* On the "Select an Archetype" window, select Configure button
* Add the remote catalog: link:http://central.maven.org/maven2/ then click OK to return
* Enter "teiid" in the filter to see the Teiid arche types.
* Select the preparser-archetype, then press Next
* Enter all the information (i.e., Group ID, Artifact ID, etc.) needed to generate the project, then click Finish

The project will be created and name according to the _*ArtifactID*_.

== Create Project using Command Line

NOTE: make sure the link:http://central.maven.org/maven2/ repository is accessible via your maven settings.

To create a custom preparser project from the command line, you can use the following template command:

***********
* TEMPLATE
***********
  
[source,java]
----

mvn archetype:generate           \
  -DarchetypeGroupId=org.teiid.arche-types               \
  -DarchetypeArtifactId=preparser-archetype          \
  -DarchetypeVersion=${archetypeVersion}     \
  -DgroupId=${groupId}                  \
  -DartifactId=${preparser-artifact-id} \
  -Dpackage=${package}    \
  -Dversion=0.0.1-SNAPSHOT      \
  -Dclass-name=${className}     \
  -Dteiid-version=${teiidVersion}
----

********
* where:
********
[source,java]
----
  -DarchetypeGroupId    -  is the group ID for the arche type to use to generate
  -DarchetypeArtifactId -  is the artifact ID for the arche type to use to generate
  -DarchetypeVersion    -  is the version for the arche type to use to generate
  -DgroupId     -  (user defined) group ID for the new preparser project pom.xml
  -DartifactId      -  (user defined) artifact ID for the new example project pom.xml
  -Dpackage     -  (user defined) the package structure where the java, module and resource files will be created
  -Dversion     -  (user defined) the version that the new connector project pom.xml will be
  -Dclass-name      -  (user defined) the class name to give the new user preparser, will become the Class Name 
  -Dteiid-version   -  the Teiid version the connector will depend upon  
----

*********
* EXAMPLE
*********

-  this is an example of the template that can be run:

[source,java]
----
mvn archetype:generate             \
  -DarchetypeGroupId=org.teiid.arche-types               \
  -DarchetypeArtifactId=preparser-archetype          \
  -DarchetypeVersion={{ book.archeTypeVersion }}    \
  -DgroupId=org.example   \
  -DartifactId=preparser-mypreparser    \
  -Dpackage=org.example.mypreparser    \
  -Dversion=0.0.1-SNAPSHOT      \
  -Dclass-name=MyPreParser      \
  -Dteiid-version={{ book.fullVersionNumber }}
----

When executed, you will be asked to confirm the package property

[source,java]
----
[INFO] Using property: groupId = org.example
[INFO] Using property: artifactId = preparser-mypreparser
[INFO] Using property: version = 0.0.1-SNAPSHOT
[INFO] Using property: package = org.example.mypreparser
[INFO] Using property: class-name = MyPreParser
[INFO] Using property: teiid-version = {{ book.fullVersionNumber }}
Confirm properties configuration:
groupId: org.teiid.preparser
artifactId: preparser-myParser
version: 0.0.1-SNAPSHOT
package: org.example.mypreparser
class-name: MyPreParser
teiid-version: {{ book.fullVersionNumber }}
 Y: : y
----

type Y (yes) and press enter, and the creation of the preparser project will be done

Upon creation, a directory based on the _*artifactId*_ will be created, that will contain the project. 'cd' into that directory and execute a test build to confirm the project was created correctly:

[source,java]
----
 mvn clean install
----

This should build successfully, and now you are ready to start adding your custom code.

