
= Additional Socket Client Settings

A "teiid-client-settings.properties" file can be used to configure Teiid low level and link:SSL_Client_Connections.html[SSL] socket connection properties. Currently only a single properties file is expected per driver/classloader combination. A sample "teiid-client-settings.properties" file can be found inside the "teiid-<version>-client.jar" file at the root called "teiid-client-settings.orig.properties". To customize the settings, extract this file, make a copy, change the property values accordingly, and place this file in the client application’s classpath before the "teiid-<version>-client.jar" file. Typically clients will not need to adjust the non-SSL properties. For reference the properties are:

[source,java]
----
########################################
# Misc Socket Configuration
########################################

#
# The time in milliseconds for socket timeouts.
# Timeouts during the initialization, handshake, or
# a server ping may be treated as an error.
#
# This is the lower bound for all other timeouts
# the JDBC login timeout.
#
# Typically this should be left at the default of 1000
# (1 second). Setting this value too low may cause read
# errors.
#

org.teiid.sockets.soTimeout=1000

#
# The max number of cached server instances
# to reuse. A server instance is a connected
# socket to a particular cluster member with
# client encryption and or SSL already established.
#
# Caching instances helps in 2 circumstances:
#  - when Connection pooling is not being used.
#  - load-balancing performance to a cluster
#    when using Connection pooling of the DataSource.
#
# This value should typically be a multiple of the
# cluster size.
#
# Set to 0 to disable instance caching.
#

org.teiid.sockets.maxCachedInstances=16

#
# Set the max time to live (in milliseconds) for non-execution
# synchronous calls.
#

org.teiid.sockets.synchronousttl=240000

#
# Set the socket receive buffer size (in bytes)
# 0 indicates that the default socket setting will be used.
#

org.teiid.sockets.receiveBufferSize=0

#
# Set the socket send buffer size (in bytes)
# 0 indicates that the default socket setting will be used.
#

org.teiid.sockets.sendBufferSize=0

#
# Set to true to enable Nagle's algorithm to conserve bandwidth
# by minimizing the number of segments that are sent.
#

org.teiid.sockets.conserveBandwidth=false

#
# Maximum number of bytes per server message.
# May need to be increased when using custom types and/or large batch sizes.
#

org.teiid.sockets.maxObjectSize=33554432


#
# Set to true to disable client ping.
# Default value is 'false' that means client ping is enable. The client ping keeps the relevant server from terminating sessions.
# If the default load balancing strategy is used, then client ping is necessary.
#
org.teiid.sockets.DisablePing=false
----

NOTE: All properties listed in "teiid-client-settings.properties" can also be set as System properties.

