
[id="client-dev-Connecting_to_a_Teiid_Server-Connecting-to-a-bookproductnameFull-Server"]
= Connecting to a {{ book.productnameFull }} Server

The {{ book.productnameFull }} JDBC API provides Java Database Connectivity (JDBC) access to a Virtual Database (VDB) deployed on {{ book.productnameFull }}. The {{ book.productnameFull }} JDBC API is compatible with the JDBC 4.0 specification; however, it is not compatible with some methods. You cannot use some advanced features, such as updatable result sets or SQL3 data types.

Java client applications connecting to a {{ book.productnameFull }} Server will need to use at least the Java 1.8 JDK. Earlier versions of Java are not compatible.  You may attempt to use a client driver from earlier Teiid versions that were compatible with the target JRE.

{% if book.targetWildfly %}
Support for {{ book.productnameFull }} clients and servers older than version 8 has been dropped from {{ book.productnameFull }} 10.2 and later.

Before you can connect to the {{ book.productnameFull }} Server using the {{ book.productnameFull }} JDBC API, please do following tasks.


1.  Install the {{ book.productnameFull }} Server. See the "Admin Guide" for instructions.
2.  Build a Virtual Database (VDB). Check the "Reference Guide" for instructions on how to build a VDB. If you do not know what VDB is, then start with this http://www.jboss.org/teiid/basics/virtualdatabases.html[document].
3.  Deploy the VDB into {{ book.productnameFull }} Server. Check link:../admin/Administrators_Guide.adoc[Administrator’s Guide] for instructions.
4.  Start the {{ book.productnameFull }} Server ({{ book.asName }}), if it is not already running.
{% endif %}

After you deploy the virtual database, client applications can connect to it and issue SQL queries against it using the JDBC API. If you are new to JDBC, refer to the Java documentation about http://docs.oracle.com/javase/tutorial/jdbc/index.html[JDBC]. {{ book.productnameFull }} ships with `teiid-_VERSION_NUMBER_-jdbc.jar` that is available from the http://teiid.io/teiid_wildfly/downloads/[Teiid.io downloads].

{% if book.targetWildfly or book.targetSpring %}
You can also obtain the {{ book.productnameFull }} JDBC from the Maven repository at https://oss.sonatype.org/content/repositories/releases/ using the coordinates:
{% else %}
You can also obtain the {{ book.productnameFull }} JDBC from the Red Hat Maven repository at https://maven.repository.redhat.com/ga/org/teiid/
{% endif %}

[source,xml,subs="+quotes"]
----
<dependency>
  <groupId>org.teiid</groupId>
  <artifactId>teiid</artifactId>
  <classifier>jdbc</classifier>
  <version>__$versionNumber__</version>
</dependency>
----

where `versionNumber` is the version of the most recent {{book.productnameFull}} release.

Important classes in the client JAR:

* `org.teiid.jdbc.TeiidDriver`- allows JDBC connections using the {{ book.javaVersionUrl }}/docs/api/java.sql/java/sql/DriverManager.html[DriverManager] class.
* `org.teiid.jdbc.TeiidDatasource`- allows JDBC connections using the {{ book.javaVersionUrl }}/docs/api/java.sql/javax/sql/DataSource.html[DataSource] {{ book.javaVersionUrl }}/docs/api/java.sql/javax/sql/XADataSource.html[XADataSource] class. You should use this class to create managed or XA connections.

Once you have established a connection with the {{ book.productnameFull }} Server, you can use standard JDBC API classes to interrogate metadata and execute queries.

[id="client-dev-Connecting_to_a_Teiid_Server-OpenTracing-Support"]
== OpenTracing compatibility

http://opentracing.io/[OpenTracing] is optional for the client driver. For remote connections to propagate the span the driver must have the appropriate OpenTracing jars in its classpath.  This can be done via a maven dependency:

[source,xml]
----
<dependency>
    <groupId>io.opentracing</groupId>
    <artifactId>opentracing-util</artifactId>
    <version>${version.opentracing}</version>
</dependency>
----

where `version.opentracing` is defined in the project integration bom.  

Alternately, you can manually include the `opentracing-util`, `opentracing-api`, and `opentracing-noop` jar files as needed by the tooling or other environment where the {{ book.productnameFull }} client jar is utilized.

OpenTracing support in the client and server requires that the respective runtimes have an appropriate tracing client installed and available via the GlobalTracer.
