
[id="client-dev-JDBC_Support-JDBC-Support"]
= JDBC compatibility

{{ book.productnameFull }} provides a robust JDBC driver that implements most of the JDBC API according to the latest specification and compatible Java version. Most tooling designed to work with JDBC should work seamlessly with the {{ book.productnameFull }} driver. When in doubt, see {% if book.targetDVProd %}xref:client-dev-Unsupported_JDBC_Methods-Unsupported-JDBC-Methods{% else %}link:Unsupported_JDBC_Methods.adoc{% endif %}[Incompatible JDBC Methods] for functionality that has yet to be implemented.

If your needs go beyond JDBC, {{ book.productnameFull }} has also provided {% if book.targetDVProd %}xref:client-dev-JDBC_Extensions-JDBC-Extensions{% else %}link:JDBC_Extensions.adoc{% endif %}[JDBC Extensions] for asynch handling, federation, and other features.

[id="client-dev-JDBC_Support-Generated-Keys"]
== Generated Keys

{{ book.productnameFull }} can return generated keys for JDBC sources and from {{ book.productnameFull }} temp tables with SERIAL primary key columns. However the current implementation will return only the last set of keys generated and will return the key results directly from the source - no view projection of other intermediate handling is performed. For most scenarios (single source inserts) this handling is sufficient. A custom solution may need to be developed if you are using a FOR EACH ROW instead of trigger to process your inserts and target multiple tables that each return generated keys. It is possible to develop a UDF that also manipulates the returned generated keys - see the `org.teiid.CommandContext` methods dealing with generated keys for more.

NOTE: You cannot use Generated Keys when the JDBC Batched updates is used to insert the values into the source table.
