[id="client-dev-OData_Support-OData-Support"]
= OData Support

[id="client-dev-OData_Support-What-is-OData"]
== What is OData

The Open Data Protocol (OData) is a Web protocol for querying and updating data that provides a way to unlock your data and free it from silos that exist in applications today. OData does this by applying and building upon Web technologies such as HTTP, Atom Publishing Protocol (AtomPub) and JSON to provide access to information from a variety of applications, services, and stores. The protocol emerged from experiences implementing AtomPub clients and servers in a variety of products over the past several years. OData is used to expose and access information from a variety of sources including, but not limited to, relational databases, file systems, content management systems and traditional Web sites.

OData is consistent with the way the Web works - it makes a deep commitment to URIs for resource identification and commits to an HTTP-based, uniform interface for interacting with those resources (just like the Web). This commitment to core Web principles allows OData to enable a new level of data integration and interoperability across a broad range of clients, servers, services, and tools.

copied from http://odata.org[http://odata.org]

[id="client-dev-OData_Support--bookproductnameFull-Support-for-OData"]
== {{ book.productnameFull }} Support for OData

{{ book.productnameFull }} provides link:OData4_Support.adoc[OData Version 4.0] support.

{% if book.targetWildfly %}
When a user successfully deploys a VDB into a {{ book.productnameFull }} Server, the OData protocol support is implicitly provided by the {{ book.productnameFull }} server without any further configuration. 

OData support is currently not available in the {{ book.productnameFull }} Embedded profile. 

OData support is implemented and deployed through WAR file(s). Access is similar to accessing to any web resources deployed on the container. The war file(s) are located at <container root>/modules/org/jboss/teiid/deployments/*.war.
  
Legacy OData Version 2.0 support has been removed, but could be maintained as it's own project - please contact the community if you still need this feature and want to maintain it.
{% endif %}  

