
= XML extensions

The XML extensions apply on to XML resutls from queries to XML document models, and not to XML produced by SQL/XML or read from some other source.

== Document formatting

The PROP_XML_FORMAT execution property can be set to modify the way that XML documents are formatted from XML document models. Valid values for the constant are defined in the same ExecutionProperties interface:

1.  `XML_TREE_FORMAT`- Returns a version of the XML formatted for display. The XML will use line breaks and tabs as appropriate to format the XML as a tree. This format is slower due to the formatting time and the larger document size.
2.  `XML_COMPACT_FORMAT`- Returns a version of the XML formatted for optimal performance. The XML is a single long string without any unnecessary white space.
3.  Not Set - If no format is set, the formatting flag on the XML document in the original model is honored. This may produce either the "tree" or "compact" form of the document depending on the document setting.

== Schema validation

The `PROP_XML_VALIDATION` execution property can be set to indicate that the server should validate XML document model documents against their schema before returning them to the client. If schema validation is on, then the server send a SQLWarning if the document does not conform to the schema it is associated with. Using schema validation will reduce the performance of your XML queries.

