= Summary

. link:Legal_Notice.adoc[Legal Notice]

. link:reference/Reference_Guide.adoc[Reference Guide]
.. link:reference/Data_Sources.adoc[Data Sources]
.. link:reference/vdb_guide.adoc[Virtual Databases]
... link:reference/vdb_properties.adoc[VDB Properties]
... link:reference/DDL_Metadata.adoc[Schema Object DDL]
... link:reference/DDL_Domain.adoc[Domain DDL]
.. link:reference/SQL_Support.adoc[SQL Support]
... link:reference/Identifiers.adoc[Identifiers]
... link:reference/Expressions.adoc[Expressions]
... link:reference/Criteria.adoc[Criteria]
... link:reference/Scalar_Functions.adoc[Scalar Functions]
.... link:reference/Numeric_Functions.adoc[Numeric Functions]
.... link:reference/String_Functions.adoc[String Functions]
.... link:reference/Date_Time_Functions.adoc[Date_Time Functions]
.... link:reference/Type_Conversion_Functions.adoc[Type Conversion Functions]
.... link:reference/Choice_Functions.adoc[Choice Functions]
.... link:reference/Decode_Functions.adoc[Decode Functions]
.... link:reference/Lookup_Function.adoc[Lookup Function]
.... link:reference/System_Functions.adoc[System Functions]
.... link:reference/XML_Functions.adoc[XML Functions]
.... link:reference/JSON_Functions.adoc[JSON Functions]
.... link:reference/Security_Functions.adoc[Security Functions]
.... link:reference/Spatial_Functions.adoc[Spatial Functions]
.... link:reference/Miscellaneous_Functions.adoc[Miscellaneous Functions]
.... link:reference/Nondeterministic_Function_Handling.adoc[Nondeterministic Function Handling]
... link:reference/DML_Commands.adoc[DML Commands]
.... link:reference/Set_Operations.adoc[Set Operations]
.... link:reference/Subqueries.adoc[Subqueries]
.... link:reference/WITH_Clause.adoc[WITH Clause]
.... link:reference/SELECT_Clause.adoc[SELECT Clause]
.... link:reference/FROM_Clause.adoc[FROM Clause]
..... link:reference/XMLTABLE.adoc[XMLTABLE]
..... link:reference/ARRAYTABLE.adoc[ARRAYTABLE]
..... link:reference/OBJECTTABLE.adoc[OBJECTTABLE]
..... link:reference/TEXTTABLE.adoc[TEXTTABLE]
.... link:reference/WHERE_Clause.adoc[WHERE Clause]
.... link:reference/GROUP_BY_Clause.adoc[GROUP BY Clause]
.... link:reference/HAVING_Clause.adoc[HAVING Clause]
.... link:reference/ORDER_BY_Clause.adoc[ORDER BY Clause]
.... link:reference/LIMIT_Clause.adoc[LIMIT Clause]
.... link:reference/INTO_Clause.adoc[INTO Clause]
.... link:reference/OPTION_Clause.adoc[OPTION Clause]
... link:reference/DDL_Commands.adoc[DDL Commands]
.... link:reference/Temp_Tables.adoc[Temp Tables]
.... link:reference/Alter_View.adoc[Alter View]
.... link:reference/Alter_Procedure.adoc[Alter Procedure]
.... link:reference/Alter_Trigger.adoc[Alter Trigger]
... link:reference/Procedures.adoc[Procedures]
.... link:reference/Procedure_Language.adoc[Procedure Language]
.... link:reference/Virtual_Procedures.adoc[Virtual Procedures]
.... link:reference/Update_Procedures_Triggers.adoc[Update Procedures]
... link:reference/Comments.adoc[Comments]
.. link:reference/Datatypes.adoc[Datatypes]
... link:reference/Supported_Types.adoc[Supported Types]
... link:reference/Type_Conversions.adoc[Type Conversions]
... link:reference/Special_Conversion_Cases.adoc[Special Conversion Cases]
... link:reference/Escaped_Literal_Syntax.adoc[Escaped Literal Syntax]
.. link:reference/Updatable_Views.adoc[Updatable Views]
... link:reference/Key-preserved_Table.adoc[preserved Table]
.. link:reference/Transaction_Support.adoc[Transaction Support]
... link:reference/AutoCommitTxn_Execution_Property.adoc[AutoCommitTxn Execution Property]
... link:reference/Updating_Model_Count.adoc[Updating Model Count]
... link:reference/JDBC_and_Transactions.adoc[JDBC and Transactions]
... link:reference/Limitations_and_Workarounds.adoc[Limitations and Workarounds]
.. link:reference/Data_Roles.adoc[Data Roles]
... link:reference/Permissions.adoc[Permissions]
... link:reference/Role_Mapping.adoc[Role Mapping]
... link:reference/XML_Definition.adoc[XML Definition]
... link:reference/Customizing.adoc[Customizing]
.. link:reference/System_Schema.adoc[System Schema]
... link:reference/sys_schema.adoc[SYS]
... link:reference/sysadmin_schema.adoc[SYSADMIN]
.. link:reference/Translators.adoc[Translators]
... link:reference/Amazon_S3_Translator.adoc[Amazon S3 Translator]
... link:reference/Amazon_SimpleDB_Translator.adoc[Amazon SimpleDB Translator]
... link:reference/Apache_Accumulo_Translator.adoc[Apache Accumulo Translator]
... link:reference/Apache_SOLR_Translator.adoc[Apache SOLR Translator]
... link:reference/Cassandra_Translator.adoc[Cassandra Translator]
... link:reference/couchbase_translator.adoc[Couchbase Translator]
... link:reference/Delegating_Translators.adoc[Delegating Translators]
... link:reference/File_Translator.adoc[File Translator]
... link:reference/Google_Spreadsheet_Translator.adoc[Google Spreadsheet Translator]
... link:reference/Infinispan_Translator.adoc[Infinispan Translator]
... link:reference/JDBC_Translators.adoc[JDBC Translators]
.... link:reference/Actian_Vector_Translator.adoc[Actian Vector Translator]
.... link:reference/Apache_Phoenix_Translator.adoc[Apache Phoenix Translator]
.... link:reference/Cloudera_Impala_Translator.adoc[Cloudera Impala Translator]
.... link:reference/DB2_Translator.adoc[DB2 Translator]
.... link:reference/Derby_Translator.adoc[Derby Translator]
.... link:reference/Exasol_Translator.adoc[Exasol Translator]
.... link:reference/Greenplum_Translator.adoc[Greenplum Translator]
.... link:reference/H2_Translator.adoc[H2 Translator]
.... link:reference/Hive_Translator.adoc[Hive Translator]
.... link:reference/HSQL_Translator.adoc[HSQL Translator]
.... link:reference/Informix_Translator.adoc[Informix Translator]
.... link:reference/Ingres_Translators.adoc[Ingres Translators]
.... link:reference/Intersystems_Cache_Translator.adoc[Intersystems Cache Translator]
.... link:reference/JDBC_ANSI_Translator.adoc[JDBC ANSI Translator]
.... link:reference/JDBC_Simple_Translator.adoc[JDBC Simple Translator]
.... link:reference/MetaMatrix_Translator.adoc[MetaMatrix Translator]
.... link:reference/Microsoft_Access_Translators.adoc[Microsoft Access Translators]
.... link:reference/Microsoft_SQL_Server_Translator.adoc[Microsoft SQL Server Translator]
.... link:reference/ModeShape_Translator.adoc[ModeShape Translator]
.... link:reference/MySQL_Translators.adoc[MySQL Translators]
.... link:reference/Netezza_Translator.adoc[Netezza Translator]
.... link:reference/Oracle_Translator.adoc[Oracle Translator]
.... link:reference/OSISoft_PI_Translator.adoc[OSISoft PI Translator]
.... link:reference/PostgreSQL_Translator.adoc[PostgreSQL Translator]
.... link:reference/PrestoDB_Translator.adoc[PrestoDB Translator]
.... link:reference/Redshift_Translator.adoc[Redshift Translator]
.... link:reference/SAP_Hana_Translator.adoc[SAP Hana Translator]
.... link:reference/SAPIQ_Translator.adoc[SAP IQ Translator]
.... link:reference/Sybase_Translator.adoc[Sybase Translator]
.... link:reference/Teiid_Translator.adoc[Teiid Translator]
.... link:reference/Teradata_Translator.adoc[Teradata Translator]
.... link:reference/Vertica_Translator.adoc[Vertica Translator]
... link:reference/JPA_Translator.adoc[JPA Translator]
... link:reference/LDAP_Translator.adoc[LDAP Translator]
... link:reference/Loopback_Translator.adoc[Loopback Translator]
... link:reference/Microsoft_Excel_Translator.adoc[Microsoft Excel Translator]
... link:reference/MongoDB_Translator.adoc[MongoDB Translator]
... link:reference/OData_Translator.adoc[OData Translator]
... link:reference/OData_V4_Translator.adoc[OData V4 Translator]
... link:reference/Swagger_Translator.adoc[Swagger Translator]
... link:reference/OLAP_Translator.adoc[OLAP Translator]
... link:reference/Salesforce_Translators.adoc[Salesforce Translators]
... link:reference/SAP_Gateway_Translator.adoc[SAP Gateway Translator]
... link:reference/Web_Services_Translator.adoc[Web Services Translator]
.. link:reference/Federated_Planning.adoc[Federated Planning]
... link:reference/Planning_Overview.adoc[Planning Overview]
... link:reference/Query_Planner.adoc[Query Planner]
... link:reference/Query_Plans.adoc[Query Plans]
... link:reference/Federated_Optimizations.adoc[Federated Optimizations]
... link:reference/Subquery_Optimization.adoc[Subquery Optimization]
... link:reference/XQuery_Optimization.adoc[XQuery Optimization]
... link:reference/Federated_Failure_Modes.adoc[Federated Failure Modes]
... link:reference/Conformed_Tables.adoc[Conformed Tables]
.. link:reference/Architecture.adoc[Architecture]
... link:reference/Terminology.adoc[Terminology]
... link:reference/Data_Management.adoc[Data Management]
... link:reference/Query_Termination.adoc[Query Termination]
... link:reference/Processing.adoc[Processing]
.. link:reference/BNF_for_SQL_Grammar.adoc[BNF for SQL Grammar]
