
= VDB Versioning

VDB Versioning is a feature that allows multiple versions of a VDB to be deployed at the same time with additional support to determine which version will be used. If a specific version is requested, then only that VDB may be connected to. If no version is set, then the deployed VDBs are searched for the appropriate version. This feature helps support more fluid migration scenarios.

== Version Property

When a user connects to {{ book.productnameFull }} the desired VDB version can be set as a connection property (See the link:../client-dev/Client_Developers_Guide.adoc[Client Developer’s Guide]) in JDBC or used as part of the VDB name for OData and ODBC access.

The vdb version is set in either the vdb.xxx or through a naming convention of the deployment name - vdbname.version.vdb, e.g. marketdata.2.vdb. The deployer is responsible for choosing an appropriate version number. If there is already a VDB name/version that matches the current deployment, then connections to the previous VDB will be terminated and its cache entries will be flushed. Any new connections will then be made to the new VDB.

NOTE: When setting the version in the vdb.xml or ddl file a unique deployment name must still be used as that is the name the application server internally uses for the deployment.  Using the same deployment name as a previous version will simply overwrite the older deployment.

A simple integer version actually treated as the semantic version X.0.0.  If desired a full semantic version can be used instead. A semantic version is up to three integers separated by periods.

Trailing version components that are missing are treated as zeros - version 1 is the same as 1.0.0 and version 1.1 is the same as 1.1.0.
    
JDBC and ODBC clients may use a version restriction - -vdbname.X. or vdbname.X.X. - note the trailing '.' which means a VDB that must match the partial version specified. For example vdbname.1.2. could match any 1.2.X version, but would not allow 1.3+ or 1.1 and earlier.

== Connection Type

Once deployed a VDB has an updatable property called connection type, which is used to determine what connections can be made to the VDB. The connection type can be one of:

* *NONE*- disallow new connections.
* *BY_VERSION*- the default setting. Allow connections only if the version is specified or if this is the earliest BY_VERSION vdb and there are no vdbs marked as ANY.
* *ANY*- allow connections with or without a version specified.

The connection type may be changed either through the AdminConsole or the AdminAPI.

== Deployment Scenarios

If only a select few applications are to migrate to the new VDB version, then a freshly deployed VDB would be left as BY_VERSION. This ensures that only applications that know the new version may use it.

If only a select few applications are to remain on the current VDB version, then their connection settings would need to be updated to reference the current VDB by its version. Then the newly deployed vdb would have its connection type set to ANY, which allows all new connections to be made against the newer version. If a rollback is needed in this scenario, then the newly deployed vdb would have its connection type set to NONE or BY_VERSION accordingly.

