
= Apache HBase Translator (hbase)

Also see common link:JDBC_Translators.adoc[JDBC Translator Information]

The Apache HBase Translator, known by the type name *_hbase_*, exposes querying functionality to http://hbase.apache.org/[HBase] Tables. http://phoenix.apache.org/[Apache Phoenix] is a JDBC SQL interface for HBase - see link:../admin/Phoenix_Data_Sources.adoc[Phoenix Data Sources] that is required for this translator as it pushes down commands into http://phoenix.apache.org/language/index.html[Phoenix SQL].

The DatabaseTimezone property should not be used with this translator.

The HBase Translator doesn’t support Joins. Phoenix uses the HBase Table Row ID as the Primary Key, which map to . This Translator is developed with Phoenix 4.3+ for HBase 0.98.1+.

NOTE: The translator implements INSERT/UPDATE through the Phoenix UPSERT operation. This means you can see different behavior than with standard INSERT/UPDATE - such as repeated inserts will not throw a duplicate key exception, but will instead update the row in question.

NOTE: Due to Phoenix driver limitations the importer will not look for unique constraints and defaults to not importing foreign keys.

NOTE: The translator support offset with Phoenix 4.8+, the Phoenix driver hard codes the server version in PhoenixDatabaseMetaData, not supply a way to detect the server version in runtime, if a newer driver is used with an older server, set the database version manually is necessary.

WARNING: The Phoenix driver does not have robust handling of time values.  If your time values are normalized to use a date component of 1970-01-01, then the default handling will work correctly.  If not, then the time column should be modeled as timestamp instead.
