
= Apache HBase Translator (hbase)

Also see common link:JDBC_Translators.adoc[JDBC Translator Information]

The Apache HBase Translator, known by the type name *_hbase_*, exposes querying functionality to http://hbase.apache.org/[HBase] Tables. http://phoenix.apache.org/[Apache Phoenix] is a JDBC SQL interface for HBase - see link:../admin/Phoenix_Data_Sources.adoc[Phoenix Data Sources] that is required for this translator as it pushes down commands into http://phoenix.apache.org/language/index.html[Phoenix SQL].

The DatabaseTimezone property should not be used with this translator.

The HBase Translator doesn’t support Joins. Phoenix uses the HBase Table Row ID as the Primary Key, which map to . This Translator is developed with Phoenix 4.3+ for HBase 0.98.1+.

NOTE: The translator implements INSERT/UPDATE through the Phoenix UPSERT operation. This means you can see different behavior than with standard INSERT/UPDATE - such as repeated inserts will not throw a duplicate key exception, but will instead update the row in question.

NOTE: Due to Phoenix driver limitations the importer will not look for unique constraints and defaults to not importing foreign keys.
