// Assembly included in the following assemblies:
// as_sql-support.adoc

[id="dml-commands"]
= DML commands

{{ book.productnameFull }} supports SQL for issuing queries and for defining view transformations. 
For more information about how SQL is used in virtual procedures and update procedures, 
see xref:procedure-language[Procedure language]. 
Nearly all these features follow standard SQL syntax and functionality, so you can use any SQL reference for more information.

There are 4 basic commands for manipulating data in SQL, corresponding to the create, read, update, and delete (CRUD) operations: 
INSERT, SELECT, UPDATE, and DELETE. 
A MERGE statement acts as a combination of INSERT and UPDATE.

You can also execute procedures by using the EXECUTE command, procedural relational command. 
For more information, see xref:procedural-relational-command[Procedural relational command],
or xref:anonymous-procedure-block[Anonymous procedure block].

{% if not book.targetWildfly and not book.targetSpring %}
include::r_set-operations.adoc[leveloffset=+1]
include::r_select-command.adoc[leveloffset=+1]
include::r_values-command.adoc[leveloffset=+1]
include::as_update-commands.adoc[leveloffset=+1]
include::r_subqueries.adoc[leveloffset=+1]
include::r_with-clause.adoc[leveloffset=+1]
include::r_select-clause.adoc[leveloffset=+1]
include::as_from-clause.adoc[leveloffset=+1]
include::r_where-clause.adoc[leveloffset=+1]
include::r_groupby-clause.adoc[leveloffset=+1]
include::r_having-clause.adoc[leveloffset=+1]
include::r_orderby-clause.adoc[leveloffset=+1]
include::r_limit-clause.adoc[leveloffset=+1]
include::r_into-clause.adoc[leveloffset=+1]
include::r_option-clause.adoc[leveloffset=+1]
{% endif %}
