// Assembly included in the following assemblies:
// as_dv_reference.adoc
[id="data-roles"]
= Data roles

Data roles, also called entitlements, are sets of permissions defined per virtual database that specify data access permissions (create, read, update, delete). 
Data roles use a fine-grained permission system that {{ book.productnameFull }} will enforce at runtime and provide audit log entries for access violations. 
{% if book.targetWildfly %}See link:../admin/Logging.adoc[Logging] and link:../dev/Custom_Logging.adoc[Custom Logging] for more.{% endif %}

Before you apply data roles, you might want to restrict source system access through the fundamental design of your virtual database. 
Foremost, {{ book.productnameFull }} can only access source entries that are represented in imported metadata. 
You should narrow imported metadata to only what is necessary for use by your virtual database.

If data role validation is enabled and data roles are defined in a virtual database, then access permissions will be enforced 
by the {{ book.productnameFull }} server. The use of data roles may be disabled system wide by removing the 
setting for the `teiid` subsystem policy-decider-module. Data roles also have built-in xref:security-functions[security functions] 
that can be used for row-based and other authorization checks.

WARNING: A virtual database that is deployed without data roles can be accessed by any authenticated user. {% if book.targetWildfly %}If you want to 
ensure some attempt has been made at securing access, then set the data-roles-required configuration element to true 
via the CLI or in the standalone.xml on the teiid subsystem.{% endif %}

TIP: By default, non-hidden schema metadata is only visible over JDBC/pg if the user is permissioned in some way for the given object. 
OData access provides all non-hidden metadata by default. 
To configure JDBC/pg to also make all non-hidden schema metadata visible to all authenticated users, 
set the environment/system property `org.teiid.metadataRequiresPermission` to false.

{% if targetDVProd %}
include::r_permissions.adoc[leveloffset=+1]
include::r_role-mapping.adoc[leveloffset=+1]


//include::r_xml-definition.adoc[leveloffset=+1] <== Wildfly
//include::r_customizing.adoc[leveloffset=+1] <== Wildfly
{% endif %}