// Assembly included in the following assemblies:
// as_sql-support.adoc

[id="dml-commands"]
= DML commands

You can use SQL in {{ book.productnameFull }} to issue queries and define view transformations. 
For more information about how SQL is used in virtual procedures and update procedures, 
see {% if book.targetDVProd %}xref:procedure-language{% else %}link:as_procedure-language.adoc{% endif %}[Procedure language]. 
Nearly all these features follow standard SQL syntax and functionality, so you can use any SQL reference for more information.

There are 4 basic commands for manipulating data in SQL, corresponding to the create, read, update, and delete (CRUD) operations: 
INSERT, SELECT, UPDATE, and DELETE. 
A MERGE statement acts as a combination of INSERT and UPDATE.

You can also execute procedures by using the EXECUTE command, procedural relational command. 
For more information, see {% if book.targetDVProd %}xref:procedural-relational-command{% else %}link:r_procedural-relational-command.adoc{% endif %}[Procedural relational command],
or {% if book.targetDVProd %}xref:anonymous-procedure-block{% else %}link:r_anonymous-procedure-block.adoc{% endif %}[Anonymous procedure block].

{% if book.targetDVProd %}
include::r_set-operations.adoc[leveloffset=+1]
include::r_select-command.adoc[leveloffset=+1]
include::r_values-command.adoc[leveloffset=+1]
include::as_update-commands.adoc[leveloffset=+1]
include::r_subqueries.adoc[leveloffset=+1]
include::r_with-clause.adoc[leveloffset=+1]
include::r_select-clause.adoc[leveloffset=+1]
include::as_from-clause.adoc[leveloffset=+1]
include::r_where-clause.adoc[leveloffset=+1]
include::r_group-by-clause.adoc[leveloffset=+1]
include::r_having-clause.adoc[leveloffset=+1]
include::r_order-by-clause.adoc[leveloffset=+1]
include::r_limit-clause.adoc[leveloffset=+1]
include::r_into-clause.adoc[leveloffset=+1]
include::r_option-clause.adoc[leveloffset=+1]
{% endif %}
