// Assembly included in the following assemblies:
// as_dv_reference.adoc
[id="system-schema"]
= System schema

The built-in SYS and SYSADMIN schemas provide metadata tables and procedures against the current virtual database.

By default, a system schema for ODBC metadata pg_catalog is also exposed. -- however, that should be considered for general use.

.Metadata visibility

The SYS system schema tables and procedures are always visible and accessible.

When xref:data-roles[data roles] are in use, users can view only the tables, views, and procedure metadata entries that they 
have permissions to access. 
All columns of a key must be accessible for an entry to be visible.  

NOTE: To make all metadata visible to any authenticated user, set the environment/system property `org.teiid.metadataRequiresPermission` to false.

NOTE: If you use data roles, visibility of entries can be affected by the caching of system metadata.

{% if book.targetDVProd %}
include::r_sys-schema.adoc[leveloffset=+1]
include::r_sysadmin-schema.adoc[leveloffset=+1]
{% endif %}