// Assembly included in the following assemblies:
// as_dv_reference.adoc
[id="transaction-support"]
= Transaction support

{{ book.productnameFull }} utilizes XA transactions for participating in global transactions and for demarcating its local and command scoped transactions. 

{% if book.targetWildfly %}
http://narayana.io/[Narayana] is used by {{ book.productnameFull }} as its transaction manager.
{% endif %}
{% if book.targetWildfly %}
http://narayana.io/[Narayana] is optionally used by {{ book.productnameFull }} as its transaction manager. 
In single source, or scenarios utilizing only non-XA sources, then the Spring platform transaction manager may be used.
{% endif %}
For information about advanced transaction technologies that are provided for {{ book.productnameFull }} through the Narayana community project, 
see http://narayana.io/documentation/index.html[the Narayana documentation].

.*{{ book.productnameFull }} transaction scopes*
|===
|Scope |Description

|Command
|Treats the user command as if all source commands are executed within the scope of the same transaction. 
The link:AutoCommitTxn_Execution_Property.adoc[AutoCommitTxn] execution property controls the behavior of command level transactions.

|Local
|The transaction boundary is local defined by a single client session.

|Global
|{{ book.productnameFull }} participates in a global transaction as an XA resource.
|===

The default transaction isolation level for {{ book.productnameFull }} is READ_COMMITTED.

{% if not book.targetWildfly and not book.targetSpring %}
include::r_autocommittxn-execution-property.adoc[leveloffset=+1]
include::r_updating-model-count.adoc[leveloffset=+1]
include::r_jdbc-and-transactions.adoc[leveloffset=+1]
//include::r_transactional-behavior-with-wildfly-data-source-types.adoc[leveloffset=+1] <-- Wildfly-specific.
include::r_limitations-and-workarounds.adoc[leveloffset=+1]
{% endif %}
