
= JPA Translator

The JPA translator, known by the type name _jpa2_, can reverse a JPA object model into a relational model, which can then be integrated with other relational or non-relational sources. For information on JPA persistence in a JBoss Application Server, see {{ book.asDocRoot }}/JPA+Reference+Guide[JPA Reference Guide].

*Properties*

The JPA Translator currently has no import or execution properties.

== Native Queries

JPA source procedures may be created using the teiid_rel:native-query extension - see link:Translators.adoc#18646290_Translators-native[Parameterizable Native Queries]. The procedure will invoke the native-query similar to an native procedure call with the benefits that the query is predetermined and that result column types are known, rather than requiring the use of ARRAYTABLE or similar functionality. See the query syntax below.

== Direct Query Procedure

NOTE: This feature is turned off by default because of the security risk this exposes to execute any command against the source. To enable this feature, link:Translators.adoc#18646290_Translators-OverrideExecutionProperties[override the execution property] called _SupportsDirectQueryProcedure_ to true.

TIP: By default the name of the procedure that executes the queries directly is *native*. link:Translators.adoc#18646290_Translators-OverrideExecutionProperties[Override the execution property] _DirectQueryProcedureName_ to change it to another name.

The JPA translator provides a procedure to execute any ad-hoc JPA-QL query directly against the source without Teiid parsing or resolving. Since the metadata of this procedure’s results are not known to Teiid, they are returned as object array. User can use link:ARRAYTABLE.adoc[ARRAYTABLE] can be used construct tabular output for consumption by client applications. Teiid exposes this procedure with a simple query structure as below

=== Select

[source,sql]
.*Select Example*
----
SELECT x.* FROM (call jpa_source.native('search;FROM Account')) w,
 ARRAYTABLE(w.tuple COLUMNS "id" string , "type" string, "name" String) AS x
----

from the above code, the "search" keyword followed by a query statement - see link:Translators.adoc#18646290_Translators-native[Parameterizable Native Queries] to substitute parameter values.

=== Delete

[source,sql]
.*Delete Example*
----
SELECT x.* FROM (call jpa_source.native('delete;<jpa-ql>')) w,
 ARRAYTABLE(w.tuple COLUMNS "updatecount" integer) AS x
----

form the above code, the "delete" keyword followed by JPA-QL for delete operation.

=== Update

[source,sql]
.*Create Example*
----
SELECT x.* FROM
 (call jpa_source.native('update;<jpa-ql>')) w,
 ARRAYTABLE(w.tuple COLUMNS "update_count" integer) AS x
----

form the above code, the "update" keyword must be followed by JPA-QL for the update statement.

=== Create

[source,sql]
.*Update Example*
----
SELECT x.* FROM
 (call jpa_source.native('create;', <entity>)) w,
 ARRAYTABLE(w.tuple COLUMNS "update_count" integer) AS x
----

Create operation needs to send "create" word as marker and send the entity as a the first parameter.

