// Module included in the following assemblies:
// as_jdbc-translators.adoc
[id="cloudera-impala-translator"]
= Cloudera Impala translator (impala)

Also see common xref:jdbc-translators[JDBC Translators] information.

The Cloudera Impala translator, known by the type name *_impala_*, is for use with Cloudera Impala 1.2.1 or later.

Impala has limited support for data types. 
It is does not have native support for time/date/xml or LOBs. 
These limitations are reflected in the translator capabilities. 
A {{ book.productnameFull }} view can use these types, however the transformation would need to specify the necessary conversions. 
Note that in those situations, the evaluations will be done in the {{ book.productnameFull }} engine.

Do not use the `DatabaseTimeZone` translator property with the Impala translator.

Impala only supports EQUI join, so using any other joins types on its source tables will result in inefficient queries.

To write criteria based on partitioned columns, model them on the source table, but do not include them in selection columns.

NOTE: Impala Hive importer does not have concept of catalog or source schema, nor does it import keys, procedures, indexes, etc.

.Impala specific importer properties

useDatabaseMetaData:: Set to true to use the normal import logic with the option to import index information disabled. Defaults to false.

If the value of `useDatabaseMetaData` is false, the typical JDBC `DatabaseMetaData` calls are not used, so not all of the common JDBC importer properties 
are applicable to Impala. 
You may still use `excludeTables`, regardless.

IMPORTANT: Some versions of Impala require the use of a `LIMIT` when performing an `ORDER BY`. 
If no default is configured in Impala, an exception can occur when a {{ book.productnameFull }} query with an `ORDER BY` but no `LIMIT` is issued. 
You should set an Impala-wide default, or configure the connection pool to use a new connection SQL string to issue a `SET DEFAULT_ORDER_BY_LIMIT` statement. 
For more information about Impala limit options, such as how to control what happens when the limit is exceeded, see the Cloudera documentation. 

NOTE: If the Impala JDBC driver has problems processing `PreparedStatements` or parsing statements in general, try disabling `useBindVariables`.
For more information, see https://issues.redhat.com/browse/TEIID-4610.
