// Module included in the following assemblies:
// as_sql-support.adoc
[id="explain-statements"]
= Explain statements

You can use an EXPLAIN statement to obtain a query plan. 
This is built into the language support and is the preferred mechanism when using the pg/ODBC transport. 
If you are using a Teiid JDBC client, you can also use SET/SHOW statements. 
For more information about SET and SHOW statements, see the Client Developer's Guide. 
//../client_dev/SET_Statement.adoc[

.Usage

[source,sql]
----
EXPLAIN [(explainOption [, ...])] statement

explainOption := 
      ANALYZE [TRUE|FALSE] 
    | FORMAT {TEXT|YAML|XML}
----
 
If no options are specified, by default the plan is provided in text format without executing the query.  

If you specify `ANALYZE` or `ANALYZE TRUE`, then the statement is executed, unless the client has set the `NOEXEC` option. 
The resulting plan will include runtime node statistics from the fully executed statement.
All side effects, including updates, will still occur. 
You might need to use a transaction to rollback any unwanted side effects.

{% if book.targetWildfly or book.targetSpring %}

While this is superficially the same syntax as PostgreSQL, the plan provided in the various formats 
is the same that has been provided by Teiid in prior versions.

{% endif %}

For more information about how to interpret results, see xref:query-plans[Query plans]. 

.Example

[source,sql]
----
EXPLAIN (analyze) select * from really_complicated_view
----

Returns a text-formatted plan from an actual run of the given statement.
