// Module included in the following assemblies:
// as_translators.adoc
[id="file-translator"]
= File translator

The file translator, known by the type name _file_, exposes stored procedures to leverage file resources. 
The translator is typically used with the `TEXTTABLE` or `XMLTABLE` functions to consume CSV or XML formatted data.

.*Execution properties*

|===
|Name |Description |Default

|Encoding
|The encoding that should be used for CLOBs returned by the getTextFiles procedure. 
The value should match an encoding known to {{ book.productnameFull }}. 
For more information, see _TO_CHARS_ and _TO_BYTES_ in xref:string-functions.adoc[String functions].
|The system default encoding.

|ExceptionIfFileNotFound
|Throw an exception in getFiles or getTextFiles if the specified file/directory does not exist.
|true 
|===

TIP: For information about how to set properties, see the following example, and _Override execution properties_ in xref:translators[Translators].

.Example: Virtual datbase DDL override 
[source,sql]
----
CREATE SERVER "file-override" 
    FOREIGN DATA WRAPPER file 
    OPTIONS(
        Encoding 'ISO-8859-1', "ExceptionIfFileNotFound" false
    );
    
CREATE SCHEMA file SERVER "file-override";
----

{% if book.targetWildfly %}
VDB XML Override Example
[source,xml]
----
<model name="file">
    <source name="file" translator-name="file-override" connection-jndi-name="java:/file"/>
</model>

<translator name="file-override" type="file">
    <property name="Encoding" value="ISO-8859-1"/>
    <property name="ExceptionIfFileNotFound" value="false"/>
</translator>
----
{% endif %}

.Usage

.getFiles

[source,sql]
----
getFiles(String pathAndPattern) returns 
TABLE(file blob, filePath string, lastModified timestamp, created timestamp, size long)
----

Retrieve all files as BLOBs matching the given path and pattern.

[source,sql]
----
call getFiles('path/*.ext')
----

If the path is a directory, then all files in the directory are returned. 
If the path matches a single file, the file is returned. 

The `*` character is treated as a wildcard to match any number of characters in the path name. Zero or matching files will be returned.

If `*`' is not used, and if the path doesn’t exist and `ExceptionIfFileNotFound` is true, then an exception is raised.

.getTextFiles

[source,sql]
----
getTextFiles(String pathAndPattern) returns 
TABLE(file clob, filePath string, lastModified timestamp, created timestamp, size long)
----

NOTE: The size reports the number of bytes.

Retrieve all files as CLOBs matching the given path and pattern.

[source,sql]
----
call getTextFiles('path/*.ext')
----

Retrieves the same files `getFiles`, but with the difference that the results are CLOB values that use the encoding execution property as the character set.

.saveFile

Save the CLOB, BLOB, or XML value to given path

[source,sql]
----
call saveFile('path', value)
----

.deleteFile

Delete the file at the given path

[source,sql]
----
call deleteFile('path')
----

The path should reference an existing file. 
If the file does not exist and `ExceptionIfFileNotFound` is true, then an exception will be thrown. 
An exception is also thrown if the file cannot be deleted.

{% if book.targetWildfly %}
.JCA resource adapter

For configuration information, see xref:../admin/File_Data_Sources.adoc[File Data Source], the xref:../admin/Ftp_Data_Sources.adoc[FTP Data Source], 
and the Administrator's Guide in general.
{% endif %}

.Native queries

NOTE: This feature is not applicable for the File translator.

.Direct query procedure

NOTE: This feature is not applicable for the File translator.
