// Module included in the following assemblies:
// as_temp-tables.adoc
[id="foreign-temp-tables"]
= Foreign temporary tables

Unlike a local or global temporary table, a foreign temporary table is a reference to an actual source table that is created at runtime, 
rather than during the metadata load.

A foreign temporary table requires explicit creation syntax:

[source,sql]
----
CREATE FOREIGN TEMPORARY TABLE name ... ON schema
----

Where the table creation body syntax is the same as a standard CREATE FOREIGN TABLE DDL statement. 
For more information, see xref:ddl-metadata-for-domains[DDL metadata]. 
In general, usage of DDL OPTION clauses might be required to properly access the source table, 
including setting the name in the source, updatability, native types, and so forth.

The schema name must specify an existing schema/model in the VDB. 
The table will be accessed as if it is on that source. 
However within {{ book.productnameFull }} the temporary table will still be scoped the same as a non-foreign temporary table. 
This means that the foreign temporary table will not belong to a {{ book.productnameFull }} schema,
 and will be scoped to the session or procedure block where it is created.

The DROP syntax for a foreign temporary table is the same as for a non-foreign temporary table.

Neither a CREATE nor a corresponding DROP of a foreign temporary table issues a pushdown command.  
Rather, this mechanism exposes a source table for use within {{ book.productnameFull }} on a temporary basis.

There are two usage scenarios for a FOREIGN TEMPORARY TABLE. 
The first is to dynamically access additional tables on the source. 
The other is to replace the usage of a {{ book.productnameFull }} local temporary table for performance reasons. 
The usage pattern for the latter case would look like:

[source,sql]
----
//- create the source table
source.native("CREATE GLOBAL TEMPORARY TABLE name IF NOT EXISTS ... ON COMMIT DELETE ROWS");
//- bring the table into {{ book.productnameFull }}
CREATE FOREIGN TEMPORARY TABLE name ... OPTIONS (UPDATABLE true)
//- use the table
...
//- forget the table
DROP TABLE name
----

Note the usage of the native procedure to pass source-specific CREATE DDL to the source. 
{{ book.productnameFull }} does not currently attempt to pushdown a source creation of a temporary table based on the CREATE statement. 
Some other mechanism, such as the native procedure shown above, must be used to first create the table. 
Also note the table is explicitly marked as updatable, since DDL defined tables are not updatable by default.

The source’s handling of temporary tables must also be understood to make this work as intended. 
Sources that use the same GLOBAL table definition for all sessions while scoping the data to be 
session-specific (such as Oracle) or sources that support session-scoped temporary tables (such as PostgreSQL) 
will work if accessed under a transaction. 
A transaction is necessary for the following reasons:

* The source on commit behavior (most likely DELETE ROWS or DROP) will ensure clean-up. 
Keep in mind that a {{ book.productnameFull }} drop does not issue a source command and is not guaranteed to occur 
(in some exception cases, loss of database connectivity, hard shutdown, and so forth).
* The source pool when using track connections by transaction will ensure that multiple uses of that source by 
{{ book.productnameFull }} will use the same connection/session and thus the same temporary table and data.

TIP: {{ book.productnameFull }} does not support the ON COMMIT clause. 
As a result, for local temporary tables, the ON COMMIT behavior for source tables is likely to be different from the default PRESERVE ROWS.
