// Module included in the following assemblies:
// as_translators.adoc
[id="google-spreadsheet-translator"]
= Google spreadsheet translator

The _google-spreadsheet_ translator is used to connect to a Google Sheets spreadsheet.

The query approach expects that the data in the worksheet has the following characteristics:

* All columns that contains data can be queried.
* Any column with an empty cell has the value retrieved as null. 
However, differentiating between null string and empty string values may not always be possible as Google treats them interchangeably. 
Where possible, the translator may provide a warning or throw an exception if it cannot differentiate between null and empty strings.
* If the first row is present and contains string values, then the row is assumed to represent the column labels.

If you are using the default native metadata import, the metadata for your Google account (worksheets and information about columns in worksheets) is loaded upon translator start up. 
If you make any changes in data types, it is advisable to restart your virtual database.

The translator can submit queries against a single sheet only. 
It provides ordering, aggregation, basic predicates, and most of the functions available in the spreadsheet query language.

The google-spreadsheet translator does not provide importer settings, but it can provide metadata for VDBs.

WARNING: If you remove all data rows from a sheet with a header that is defined in {{ book.productnameFull }}, you can no longer access the sheet through {{ book.productnameFull }}. 
The Google API will treat the header as a data row at that point, and queries to it will no longer be valid.

WARNING: Non-string fields are updated using the canonical {{ book.productnameFull }} SQL value. 
In cases where the spreadsheet is using a non-conforming locale, consider disallowing updates. 
For more information, see link:https://issues.redhat.com/browse/TEIID-4854[TEIID-4854] and the following information about the `allTypesUpdatable` import property.

.Importer properties

* _allTypesUpdatable_- Set to true to mark all columns as updatable. 
Set to false to enable update only on string or Boolean columns that are not affected by link:https://issues.redhat.com/browse/TEIID-4854[TEIID-4854]. 
Defaults to true.

{% if book.targetWildfly %}
.JCA resource adapter

The {{ book.productnameFull }} specific Google Spreadsheet Data Sources Resource Adapter should be used with this translator.
{% endif %}

.Native queries

Google spreadsheet source procedures may be created using the `teiid_rel:native-query` extension. 
For more information, see _Parameterizable native queries_ in {% if book.targetDVProd %}xref:translators{% else %}link:as_translators.adoc{% endif %}[Translators]. 
The procedure will invoke the native-query similar to an native procedure call, with the benefits that the query is predetermined, 
and that result column types are known, rather than requiring the use of ARRAYTABLE or similar functionality. 
For more information, see the _Select_ section that follows.

.Direct query procedure

NOTE: This feature is turned off by default, because of the security risk in permitting any command to execute against the data source. 
To enable this feature, set the property _SupportsDirectQueryProcedure_ to true. 
For more information, see _Override execution properties_ in {% if book.targetDVProd %}xref:translators{% else %}link:as_translators.adoc{% endif %}[Translators]. 

TIP: By default the name of the procedure that executes the queries directly is called *native*. 
You can change its name by overriding the execution property _DirectQueryProcedureName_. 
For more information, see _Override execution properties_ in {% if book.targetDVProd %}xref:translators{% else %}link:as_translators.adoc{% endif %}[Translators]. 

The Google spreadsheet translator provides a procedure to execute any ad-hoc query directly against the source without any {{ book.productnameFull }} parsing or resolving. 
Because the metadata of this procedure’s execution results are not known to {{ book.productnameFull }}, they are returned as an object array. 
You can use ARRAYTABLE to construct tabular output for consumption by client applications. For more information, see {% if book.targetDVProd %}xref:arraytable{% else %}link:r_arraytable.adoc{% endif %}[ARRAYTABLE].

{{ book.productnameFull }} exposes this procedure with a simple query structure as shown in the following example:

.Select

[source,sql]
.*Select example*
----
SELECT x.* FROM (call google_source.native('worksheet=People;query=SELECT A, B, C')) w,
 ARRAYTABLE(w.tuple COLUMNS "id" string , "type" string, "name" String) AS x
----

The first argument takes semicolon-separated (;) name-value pairs of the following properties to execute the procedure:

|===
|Property |Description |Required

|worksheet
|Google spreadsheet name.
|yes

|query
|Spreadsheet query.
|yes

|limit
|Number of rows to fetch.
|no

|offset
|Offset of rows to fetch from limit or beginning.
|no
|===
