// Module included in the following assemblies:
// as_jdbc-translators.adoc
[id="jdbc-ansi-translator"]

= JDBC ANSI translator (jdbc-ansi)

Also see common {% if book.targetDVProd %}xref:jdbc-translators{% else %}link:as_jdbc-translators.adoc{% endif %}[JDBC Translators] information.

The JDBC ANSI translator, known by the type name *_jdbc-ansi_*, works with most of the SQL constructs used in {{ book.productnameFull }}, 
except for row LIMIT/OFFSET and EXCEPT/INTERSECT. 
It translates source SQL into ANSI compliant syntax. 
This translator should be used when another more specific type is not available. 
If source exceptions arise due to the use of incompatible SQL constructs, then consider using the {% if book.targetDVProd %}xref:jdbc-simple-translator{% else %}link:r_jdbc-simple-translator.adoc{% endif %}[JDBC simple translator] 
to further restrict capabilities, or create a custom translator. 
For more information, see the 
http://teiid.github.io/teiid-documents/master/sb/dev/Translator_Development.html[Custom Translator documentation in the Teiid community].
