
= OpenAPI Translator

The OpenAPI translator, known by the type name _"openapi"_ exposes OpenAPI data sources via realational concepts and uses the {{ book.productnameFull }} WS resource adapter for making web service calls.

NOTE: *What is OpenAPI* - https://www.openapis.org/[[OpenAPI] is a simple yet powerful representation of your RESTful API. With the largest ecosystem of API tooling on the planet, thousands of developers are supporting OpenAPI in almost every modern programming language and deployment environment. With a OpenAPI-enabled API, you get interactive documentation, client SDK generation and discoverability.

This translator is compatible with OpenAPI/Swagger v2 and OpenAPI v3.

== Usage

Usage of a OpenAPI source is similar any other translator in {{ book.productnameFull }}. The metadata import is supported through the translator. the metadata is imported from source system's metadata file and then exposed as stored procedures in {{ book.productnameFull }}. The source system can be queried by executing these stored procedures in {{ book.productnameFull }} system.

NOTE: Parameter order is guaranteed by the swagger libraries.  However it is recommended that you call procedures using named, rather than positional parameters, if you rely upon the native import. 

The below is sample VDB that can read metadata from Petstore reference service on http://petstore.swagger.io/ site.

[source,xml]
----
<vdb name="petstore" version="1">
    <model visible="true" name="m">
        <property name="importer.metadataUrl" value="/swagger.json"/>
        <source name="s" translator-name="openapi" connection-jndi-name="java:/openapi"/> 
    </model>
</vdb>
----

The required resource-adapter configuration will look like

[source,xml]
----
<resource-adapter id="openapi">
    <module slot="main" id="org.jboss.teiid.resource-adapter.webservice"/>
    <transaction-support>NoTransaction</transaction-support>
    <connection-definitions>
        <connection-definition class-name="org.teiid.resource.adapter.ws.WSManagedConnectionFactory" jndi-name="java:/openapi" enabled="true" use-java-context="true" pool-name="teiid-openapi-ds">
            <config-property name="EndPoint">
                http://petstore.swagger.io/v2
            </config-property>
        </connection-definition>
    </connection-definitions>
</resource-adapter>
----

Once you configure above resource-adapter and deploy the VDB successfully, then you can connect to the VDB deployed using {{ book.productnameFull }} JDBC driver and issue SQL statements like

[source,sql]
----
EXEC findPetsByStatus(('sold',))
EXEC getPetById(1461159803)
EXEC deletePet('', 1461159803)
----

== Configuration of Translator

=== Execution Properties

Execution properties extend/limit the functionality of the translator based on the physical source capabilities. Sometimes default properties need to adjusted for proper execution of the translator.

*Execution Properties*

none


=== Importer Properties

Importer properties define the behavior of the translator during the metadata import from the physical source.

*Importer Properties*

|===
|Name |Description |Default

|metadataUrl
|URL from which to obtain the OpenAPI metadata.  May be a local file using a file: URL.
|true

|server
|The server to use.  Otherwise the first server listed will be used.
|null

|preferredProduces
|Preferred Accept MIME type header, this should be one of the OpenAPI 'produces' types;
|application/json

|preferredConsumes
|Preferred Content-Type MIME type header, this should be one of the OpenAPI 'consumer' types;
|application/json

|===

{% if book.targetWildfly %}
=== JCA Resource Adapter

The resource adapter for this translator is a link:../admin/Web_Service_Data_Sources.adoc[Web Service Data Source].
{% endif %}

NOTE: *Native Queries* - Native or direct query execution is not supported through OpenAPI translator. However, user can use Web Services Translator’s _invokehttp_ method directly to issue a Rest based call and parse results using SQLXML.

=== Limitations
- "application/xml" mime type in both "Accept" and "Content-Type" is currently not supported
- File, Map properties are currently not supported, thus any multi-part payloads are not supported
- Security metadata is currently not supported
- Custom properties that start with "x-" are not supported.
- Schema with "allof", "multipleof", "items" from JSON schema are not supported
