// Module included in the following assemblies:
// as_jdbc-translators.adoc
[id="postgresql-translator"]

= PostgreSQL translator (postgresql)

Also see common {% if book.targetDVProd %}xref:jdbc-translators{% else %}link:as_jdbc-translators.adoc{% endif %}[JDBC translators] information.

The PostgreSQL translator, known by the type name *_postgresql_*, is for use with the following PostgreSQL client and server versions:
* Client -- 8.0 or later
* Server -- 7.1 or later.

.Execution properties
PostgreSQL-specific execution properties:

PostGisVersion:: Indicates the PostGIS version in use. Defaults to 0, which means that PostGIS is not installed. 
Will be set automatically if the database version is not set.
ProjSupported:: Boolean that indicates if the PostGis version supports PROJ coordinate transformation software. 
Will be set automatically if the database version is not set.

[NOTE] 
====
Some driver versions of PostgreSQL will not associate columns to "INDEX" type tables.  
The current version of {{ book.productnameFull }} omits such tables automatically. 

ifndef::dv-product[]

Older versions of {{ book.productnameFull }} may need the importer.tableType property or other filtering set.

endif::[]
====
