// Module included in the following assemblies:
// as_jdbc-translators.adoc
[id="prestodb-translator"]
= PrestoDB translator (prestodb)

Also see common xref:jdbc-translators[JDBC translators] information.

The PrestoDB translator, known by the type name *_prestodb_*, exposes querying functionality to Presto data sources. 
In data integration respect, PrestoDB has very similar capabilities of {{ book.productnameFull }}, 
however it goes beyond in terms of distributed query execution with multiple worker nodes. 
{{ book.productnameFull }}’s execution model is limited to single execution node and focuses more on pushing the query down to sources. 
{{ book.productnameFull }} provides more complete query support and many enterprise features.

.Capabilities

The PrestoDB translator supports only `SELECT` statements with a restrictive set of capabilities. 


Because Presto exposes a relational model, {{ book.productnameFull }} can use it as it does other RDBMS sources, such as Oracle, DB2, and so forth. 
For information about configuring Presto, see the Presto documentation.

TIP: In SQL JOIN operations, Presto does not support multiple `ORDER BY` columns well. 
If errors occur during JOIN operations that involve more than one `ORDER BY` column, 
set the translator property `supportsOrderBy` to disable the use of the `ORDER BY` clause. 

NOTE: Some versions of Presto generate errors when you include null values in subqueries.

TIP: PrestoDB does not support transactions. 
To overcome issues caused by this limitation, define the datasource as non-transactional.


[NOTE]
====
By default, every catalog in Presto has an `information_schema`. 
If you have to configure multiple catalogs, duplicate table errors can cause deployment of a virtual database to fail.
To prevent duplicate table errors, use import options to filter the schemas. 
 
If you want to configure multiple Presto catalogs, set one of the following import options to filter the schemas and tables in the source:
 
* Set `catalog` to a specific catalog name to match the name of the source catalog in Presto.
* Set `schemaName` to a regular expression to filter schemas by matching result.
* Set `excludeTables` to a regular expression to filter tables by matching results.
====
