// Module included in the following assemblies:
// as_datatypes.adoc"]
[id-"special-conversion-cases"]
= Special conversion cases

.Conversion of string literals

{{ book.productnameFull }} automatically converts string literals within a SQL statement to their implied types. 
This typically occurs in a criteria comparison where an expression with a different datatype is compared to a literal string. 
For example:

[source,sql]
----
SELECT * FROM my.table WHERE created_by = '2016-01-02'
----

In the preceding example, if the `created_by` column has the data type of date, 
{{ book.productnameFull }} automatically converts the data type of the string literal to a date.

.Converting to Boolean

{{ book.productnameFull }} can automatically convert literal strings and numeric type values to Boolean values as shwon in the following table:

.Boolean conversions
|===
|Type |Literal value |Boolean value

|String
|'false'
|false

| 
|'unknown'
|null

| 
|other
|true

|Numeric
|0
|false

| 
|other
|true
|===

.Date and time conversions

{{ book.productnameFull }} can implicitly convert properly formatted literal strings 
to their associated date-related data types as shown in the following table:

.Date and time conversions
|===
|String literal format |Possible implicit conversion type

|yyyy-mm-dd
|DATE

|hh:mm:ss
|TIME

|yyyy-mm-dd[ hh:mm:ss.[fff…]]
|TIMESTAMP
|===

The preceding formats are those expected by the JDBC date types. 
For information about using other formats, see the functions `PARSEDATE`, `PARSETIME`, and `PARSETIMESTAMP` in xref:date-time-functions[Date and time functions].
