// Module included in the following assemblies:
// as_jdbc-translators.adoc
[id="sybase-translator"]

= Sybase translator (sybase)

Also see common xref:jdbc-translators[JDBC Translators] information.

The Sybase translator, known by the type name *_sybase_*, is for use with SAP ASE (Adaptive Server Enterprise), formerly
known as Sybase SQL Server, version 12.5 or later.

If you use the default native import, you can avoid exceptions during the retrieval of system table information, if you specify import properties. 
If errors occur when retrieving table information, specify a `schemaName` or `schemaPattern`, or use `excludeTables` to exclude system tables. 
For more information about using import properties, see _Importer properties_ in xref:jdbc-translators[JDBC translators].

If the name in the source metadata contains quoted identifiers (such as reserved words, or words that contain characters 
that would not otherwise be allowed), and you are using a jConnect Sybase driver, you must first configure the connection pool to enable *quoted_identifier*:

.Example: Driver URL with SQLINITSTRING

[source,sql]
----
jdbc:sybase:Tds:host.at.some.domain:5000/db_name?SQLINITSTRING=set quoted_identifier on
----

IMPORTANT: If you are using a jConnect Sybase driver and will target the source for dependent joins, set the `JCONNECT_VERSION`
to `6` or later to increase the number of values that the translator can send. 
If you do not set the `JCONNECT_VERSION`, an exception occurs with statements that have more than 481 bind values.

.Example: Driver URL with JCONNECT_VERSION

[source,sql]
----
jdbc:sybase:Tds:host.at.some.domain:5000/db_name?SQLINITSTRING=set quoted_identifier on&JCONNECT_VERSION=6
----

.Execution properties specific to Sybase

JtdsDriver_:: Indicates that the open source JTDS driver is being used. 
Defaults to false.
