
// Module included in the following assemblies:
// as_architecture.adoc
[id="terminology"]
= Terminology

{% if book.targetWildfly %}
VM or Process:: A {{ book.asName }} instance running {{ book.productnameFull }}.  
{% else %}
VM or process:: A Spring Boot instance of {{ book.productnameFull }}.  
{% endif %}

Host:: A machine that runs one or more VMs.
Service:: A subsystem that runs in a VM (often in many VMs) and provides a related set of functionality. 
In addition to these main components, the service platform makes the following core set of services available 
to the applications that are built on top of it:
  Session::: The Session service manages active session information.
  Buffer manager::: The Buffer Manager service provides access to data management for intermediate results. 
  For more information, see _Buffer management_  in {% if book.targetDVProd %}xref:data-management{% else %}link:r_data-management.adoc{% endif %}[Data management].
  Transaction::: The Transaction service manages global, local, and request scoped transactions. 
  For more information, see {% if book.targetDVProd %}xref:transaction-support{% else %}link:as_transaction-support.adoc{% endif %}[Transactions].
