
= Reference Guide 

{{ book.productnameFull }} offers a highly scalable and high performance solution to information integration. By allowing integrated and enriched data to be consumed relationally, as JSON, XML, and other formats over multiple protocols. {{ book.productnameFull }} simplifies data access for developers and consuming applications.

Commercial development support, production support, and training for {{ book.productnameFull }} is available through Red Hat. {{ book.productnameFull }} is a Professional Open Source project and a critical component of Red Hat data integration offerings.

Before one can delve into {{ book.productnameFull }} it is very important to learn few basic constructs of {{ book.productnameFull }}, like what is VDB? what is Model? etc. For that please read the http://teiid.io/about/basics/[short introduction].

If not otherwise specified versions referenced in this document refer to Teiid project versions.  Teiid or {{ book.productnameFull }} running on various platforms will have both platform and product specific versioning.

