
= Salesforce Translators

The Salesforce translator supports the SELECT, DELETE, INSERT and UPDATE operations against a Salesforce.com account. It is designed for use with the Teiid Salesforce resource adapter.

== Salesforce API Version Support

=== salesforce

The translator, known by the type name *_salesforce_*, provides Salesforce API 22.0 support. The translator must be used with the corresponding Salesforce resource adapter of the same API version. Salesforce API version 22.0 support has been deprecated.

=== salesforce-34

The translator, known by the type name of *_salesforce-34_*, provides Salesforce API 34.0 support. The translator must be used with the corresponding Salesforce resource adapter of the same API version.

=== Other API Versions

If you need connectivity to an API version other than what is built in, please utilize the project https://github.com/teiid/salesforce[https://github.com/teiid/salesforce] to generate new resource adapter / translator pair.

=== Execution Properties

|===
|Name |Description |Default

|ModelAuditFeilds
|Audit Model Fields
|false

|MaxBulkInsertBatchSize
|Batch Size to use to insert bulk inserts
|2048

|SupportsGroupBy
|Supports Group By Pushdown. Set to false to have Teiid process group by aggregations, such as those returning more than 2000 rows which error in SOQL.
|true
|===

The Salesforce translator can import metadata.

== Import Properties

|===
|Property Name |Description |Required |Default

|NormalizeNames
|If the importer should attempt to modify the object/field names so that they can be used unquoted.
|false
|true

|excludeTables
|A case-insensitive regular expression that when matched against a table name will exclude it from import. Applied after table names are retrieved. Use a negative look-ahead (?!<inclusion pattern>).* to act as an inclusion filter.
|false
|n/a

|includeTables
|A case-insensitive regular expression that when matched against a table name will be included during import. Applied after table names are retrieved from source.
|false
|n/a

|importStatstics
|Retrieves cardinalities during import using the REST API explain plan feature.
|false
|false
|===

NOTE： When both _includeTables_ and _excludeTables patterns are present during the import, the _includeTables_ pattern matched first, then the _excludePatterns_ will be applied.

TIP： Teiid translator uses Salesforce Partner API libraries to access the Salesforce system. By default Teiid uses Partner API version "22". Metadata retrieval using the translator and execution of queries against Salesforce using this metadata are *strongly* dependent upon the API version that has been used. It is required that you use same API versions for both Metadata retrieval and query execution. For this reason if you have older VDBS then you either need to re-import the metadata or keep using the default version. For any reason you need to use a different version of API than "22", then you can provide the new translator and resource-adapter combination for that API. For your convenience we provided a template project https://github.com/teiid/salesforce[https://github.com/teiid/salesforce] that you can build and deploy into Teiid system for the new version of the API. If you are using Teiid Embedded, then you could simply choose to replace the kitted salesforce jars with a later version. Up to version v34 is known to be compatible.

=== SQL Processing

Salesforce does not provide the same set of functionality as a relational database. For example, Salesforce does not support arbitrary joins between tables. However, working in combination with the Teiid Query Planner, the Salesforce connector supports nearly all of the SQL syntax supported by the Teiid.

The Salesforce Connector executes SQL commands by "pushing down" the command to Salesforce whenever possible, based on the supported capabilities. Teiid will automatically provide additional database functionality when the Salesforce Connector does not explicitly provide support for a given SQL construct. In cases where certain SQL capabilities cannot be pushed down to Salesforce, Teiid will push down the capabilities that are supported, and fetch a set of data from Salesforce. Then, Teiid will evaluate the additional capabilities, creating a subset of the original data set. Finally, Teiid will pass the result to the client.

If you are issuing queries with a group by clause and receive an error for salesforce related to queryMore not being supported, you may either add limits or set the execution property SupportsGroupBy to false.

[source,sql]
----
SELECT sum(Reports) FROM Supervisor where Division = 'customer support';
----

Neither Salesforce nor the Salesforce Connector support the sum() scalar function, but they do support CompareCriteriaEquals, so the query that is passed to Salesforce by the connector will be transformed to this query.

[source,sql]
----
SELECT Reports FROM Supervisor where Division = 'customer support';
----

The sum() scalar function will be applied by the Teiid Query Engine to the result set returned by the connector.

In some cases multiple calls to the Salesforce application will be made to support the SQL passed to the connector.

[source,sql]
----
DELETE From Case WHERE Status = 'Closed';
----

The API in Salesforce to delete objects only supports deleting by ID. In order to accomplish this the Salesforce connector will first execute a query to get the IDs of the correct objects, and then delete those objects. So the above DELETE command will result in the following two commands.

[source,sql]
----
SELECT ID From Case WHERE Status = 'Closed';
DELETE From Case where ID IN (<result of query>);
----

NOTE： The Salesforce API DELETE call is not expressed in SQL, but the above is an equivalent SQL expression.

It’s useful to be aware of unsupported capabilities, in order to avoid fetching large data sets from Salesforce and making you queries as performant as possible. See all Supported Capabilities.

== Selecting from Multi-Select Picklists

A multi-select picklist is a field type in Salesforce that can contain multiple values in a single field. Query criteria operators for fields of this type in SOQL are limited to EQ, NE, includes and excludes. The full Salesforce documentation for selecting from mullti-select picklists can be found at the following link http://www.salesforce.com/us/developer/docs/soql_sosl/Content/sforce_api_calls_soql_querying_multiselect_picklists.htm[Querying Mulit-select Picklists]

Teiid SQL does not support the includes or excludes operators, but the Salesforce connector provides user defined function definitions for these operators that provided equivalent functionality for fields of type multi-select. The definition for the functions is:

[source,sql]
----
boolean includes(Column column, String param)
boolean excludes(Column column, String param)
----

For example, take a single multi-select picklist column called Status that contains all of these values.

* current
* working
* critical

For that column, all of the below are valid queries:

[source,sql]
----
SELECT * FROM Issue WHERE true = includes (Status, 'current, working' );
SELECT * FROM Issue WHERE true = excludes (Status, 'current, working' );
SELECT * FROM Issue WHERE true = includes (Status, 'current;working, critical' );
----

EQ and NE criteria will pass to Salesforce as supplied. For example, these queries will not be modified by the connector.

[source,sql]
----
SELECT * FROM Issue WHERE Status = 'current';
SELECT * FROM Issue WHERE Status = 'current;critical';
SELECT * FROM Issue WHERE Status != 'current;working';
----

== Selecting All Objects

The Salesforce connector supports the calling the queryAll operation from the Salesforce API. The queryAll operation is equivalent to the query operation with the exception that it returns data about all current and deletedobjects in the system.

The connector determines if it will call the query or queryAll operation via reference to the isDeleted property present on each Salesforce object, and modeled as a column on each table generated by the importer. By default this value is set to False when the model is generated and thus the connector calls query. Users are free to change the value in the model to True, changing the default behaviour of the connector to be queryAll.

The behavior is different if isDeleted is used as a parameter in the query. If the isDeleted column is used as a parameter in the query, and the value is 'true' the connector will call queryAll.

[source,sql]
----
select * from Contact where isDeleted = true;
----

If the isDeleted column is used as a parameter in the query, and the value is 'false' the connector perform the default behavior will call query.

[source,sql]
----
select * from Contact where isDeleted = false;
----

== Selecting Updated Objects

If the option is selected when importing metadata from Salesforce, a GetUpdated procedure is generated in the model with the following structure:

[source,sql]
----
GetUpdated (ObjectName IN string,
    StartDate IN datetime,
    EndDate IN datetime,
    LatestDateCovered OUT datetime)
returns
    ID string
----

See the description of the http://www.salesforce.com/us/developer/docs/api/Content/sforce_api_calls_getupdated.htm[GetUpdated] operation in the Salesforce documentation for usage details.

== Selecting Deleted Objects

If the option is selected when importing metadata from Salesforce, a GetDeleted procedure is generated in the model with the following structure:

[source,sql]
----
GetDeleted (ObjectName IN string,
    StartDate IN datetime,
    EndDate IN datetime,
    EarliestDateAvailable OUT datetime,
    LatestDateCovered OUT datetime)
returns
    ID string,
    DeletedDate datetime
----

See the description of the http://www.salesforce.com/us/developer/docs/api/Content/sforce_api_calls_getdeleted.htm[GetDeleted] operation in the Salesforce documentation for usage details.

== Relationship Queries

Salesforce does not support joins like a relational database, but it does have support for queries that include parent-to-child or child-to-parent relationships between objects. These are termed Relationship Queries. The SalesForce connector supports Relationship Queries through Outer Join syntax.

[source,sql]
----
SELECT Account.name, Contact.Name from Contact LEFT OUTER JOIN Account
on Contact.Accountid = Account.id
----

This query shows the correct syntax to query a SalesForce model with to produce a relationship query from child to parent. It resolves to the following query to SalesForce.

[source,sql]
----
SELECT Contact.Account.Name, Contact.Name FROM Contact
----

[source,sql]
----
select Contact.Name, Account.Name from Account Left outer Join Contact
on Contact.Accountid = Account.id
----

This query shows the correct syntax to query a SalesForce model with to produce a relationship query from parent to child. It resolves to the following query to SalesForce.

[source,sql]
----
SELECT Account.Name, (SELECT Contact.Name FROM
Account.Contacts) FROM Account
----

See the description of the http://www.salesforce.com/us/developer/docs/api/index_Left.htm#StartTopic=Content/sforce_api_calls_soql_relationships.htm[Relationship Queries] operation in the SalesForce documentation for limitations.

== Bulk Insert Queries

SalesForce translator also supports bulk insert statements using JDBC batch semantics or SELECT INTO semantics. The batch size is determined by the execution property _MaxBulkInsertBatchSize_, which can be overridden in the vdb.xml file. The default value of the batch is 2048. The bulk insert feature uses the async REST based API exposed by Salesforce for execution for better performance.

== Supported Capabilities

The following are the the connector capabilities supported by the Salesforce Connector. These SQL constructs will be pushed down to Salesforce.

* SELECT command
* INSERT Command
* UPDATE Command
* DELETE Command
* CompareCriteriaEquals
* InCriteria
* LikeCriteria - Supported for String fields only.
* RowLimit
* AggregatesCountStar
* NotCriteria
* OrCriteria
* CompareCriteriaOrdered
* OuterJoins with join criteria KEY

== Native Queries

Salesforce procedures may optionally have native queries associated with them - see link:Translators.adoc#18646290_Translators-native[Parameterizable Native Queries]. The operation prefix (select;, insert;, update;, delete; - see below for more) must be present in the native-query, but it will not be issued as part of the query to the source.

[source,sql]
.*Example DDL for a SF native procedure*
----
CREATE FOREIGN PROCEDURE proc (arg1 integer, arg2 string) OPTIONS ("teiid_rel:native-query" 'search;SELECT ... complex SOQL ... WHERE col1 = $1 and col2 = $2') returns (col1 string, col2 string, col3 timestamp);
----

=== Direct Query Procedure

This feature is turned off by default because of the security risk this exposes to execute any command against the source. To enable this feature, link:Translators.adoc#18646290_Translators-OverrideExecutionProperties[override the execution property] called _SupportsDirectQueryProcedure_ to true.

TIP: By default the name of the procedure that executes the queries directly is *native*. link:Translators.adoc#18646290_Translators-OverrideExecutionProperties[Override the execution property] _DirectQueryProcedureName_ to change it to another name.

The Salesforce translator provides a procedure to execute any ad-hoc SOQL query directly against the source without Teiid parsing or resolving. Since the metadata of this procedure’s results are not known to Teiid, they are returned as an object array. link:ARRAYTABLE.adoc[ARRAYTABLE] can be used construct tabular output for consumption by client applications. Teiid exposes this procedure with a simple query structure as follows:

=== Select

[source,sql]
.*Select Example*
----
SELECT x.* FROM (call sf_source.native('search;SELECT Account.Id, Account.Type, Account.Name FROM Account')) w,
 ARRAYTABLE(w.tuple COLUMNS "id" string , "type" string, "name" String) AS x
----

from the above code, the "search" keyword followed by a query statement.

NOTE: The SOQL is treated as a parameterized native query so that parameter values may be inserted in the query string properly - see link:Translators.adoc#18646290_Translators-native[Parameterizable Native Queries]

The results returned by search may contain the object Id as the first column value regardless of whether it was selected. Also queries that select columns from multiple object types will not be correct.

=== Delete

[source,sql]
.*Delete Example*
----
SELECT x.* FROM (call sf_source.native('delete;', 'id1', 'id2')) w,
 ARRAYTABLE(w.tuple COLUMNS "updatecount" integer) AS x
----

form the above code, the "delete;" keyword followed by the ids to delete as varargs.

=== Create or Update

[source,sql]
.*Create Example*
----
SELECT x.* FROM
 (call sf_source.native('create;type=table;attributes=one,two,three', 'one', 2, 3.0)) w,
 ARRAYTABLE(w.tuple COLUMNS "update_count" integer) AS x
----

form the above code, the "create" or "update" keyword must be followed by the following properties. Attributes must be matched positionally by the procedure variables - thus in the example attribute two will be set to 2.

|===
|Property Name |Description |Required

|type
|Table Name
|Yes

|attributes
|comma separated list of names of the columns
|no
|===

The values for each attribute is specified as separate argument to the "native" procedure.

Update is similar to create, with one more extra property called "id", which defines identifier for the record.

[source,sql]
.*Update Example*
----
SELECT x.* FROM
 (call sf_source.native('update;id=pk;type=table;attributes=one,two,three', 'one', 2, 3.0)) w,
 ARRAYTABLE(w.tuple COLUMNS "update_count" integer) AS x
----

TIP: By default the name of the procedure that executes the queries directly is called native, however user can + set override execution property vdb.xml file to change it.

== JCA Resource Adapter

The resource adapter for this translator is provided through https://docs.jboss.org/author/display/TEIID/Salesforce+Data+Sources[Salesforce Data Sources]. Refer to Admin Guide for configuration.

