
= Security Functions

Security functions provide the ability to interact with the security system or to hash/encrypt values.

== HASROLE

Whether the current caller has the Teiid data role roleName.

[source,sql]
----
hasRole([roleType,] roleName)
----

_roleName_ must be a string, the return type is boolean.

The two argument form is provided for backwards compatibility. roleType is a string and must be `data'.

Role names are case-sensitive and only match Teiid link:Data_Roles.adoc[Data Roles]. JAAS roles/groups names are not valid for this function - unless there is corresponding data role with the same name.

== MD5

Computes the MD5 hash of the value.

[source,sql]
----
MD5(value)
----

value must be a string or varbinary, the return type is varbinary.  String values are first converted to their UTF-8 byte representation.

== SHA1

Computes the SHA-1 hash of the value.

[source,sql]
----
SHA1(value)
----

value must be a string or varbinary, the return type is varbinary.  String values are first converted to their UTF-8 byte representation.

== SHA2_256

Computes the SHA-2 256 bit hash of the value.

[source,sql]
----
SHA2_256(value)
----

value must be a string or varbinary, the return type is varbinary.  String values are first converted to their UTF-8 byte representation.

== SHA2_512

Computes the SHA-2 512 bit hash of the value.

[source,sql]
----
SHA2_512(value)
----

value must be a string or varbinary, the return type is varbinary.  String values are first converted to their UTF-8 byte representation.