
= Spatial Functions

Spatial functions provide functionality for working with http://www.opengeospatial.org/[geospatial] data. Teiid relies on the http://www.vividsolutions.com/jts/JTSHome.htm[JTS Topology Suite] to provide partial support for the OpenGIS Simple Features Specification For SQL Revision 1.1. Please refer to the https://portal.opengeospatial.org/files/?artifact_id=829[specification] for more details about particular functions.

Most Geometry support is limited to two dimensions due to the WKB and WKT formats.

NOTE: Geometry support is still evolving. There may be minor differences between Teiid and pushdown results that will need to be further refined.

== Conversion Functions

=== ST_GeomFromText

Returns a geometry from a Clob in WKT format.

[source,sql]
----
ST_GeomFromText(text [, srid])
----

text is a clob, srid is an optional integer. Return value is a geometry.

=== ST_GeomFromWKB/ST_GeomFromBinary

Returns a geometry from a blob in WKB format.

[source,sql]
----
ST_GeomFromWKB(bin [, srid])
----

bin is a blob, srid is an optional integer. Return value is a geometry.

=== ST_GeomFromGeoJSON

Returns a geometry from a Clob in GeoJSON format.

[source,sql]
----
ST_GeomFromGeoJson(text [, srid])
----

text is a clob, srid is an optional integer. Return value is a geometry.

=== ST_GeomFromGML

Returns a geometry from a Clob in GML2 format.

[source,sql]
----
ST_GeomFromGML(text [, srid])
----

text is a clob, srid is an optional integer. Return value is a geometry.

=== ST_AsText

[source,sql]
----
ST_GeomAsText(geom)
----

geom is a geometry. Return value is clob in WKT format.

=== ST_AsBinary

[source,sql]
----
ST_GeomAsBinary(geom)
----

geom is a geometry. Return value is a blob in WKB format.

=== ST_AsGeoJSON

[source,sql]
----
ST_GeomAsGeoJSON(geom)
----

geom is a geometry. Return value is a clob with the GeoJSON value.

=== ST_AsGML

[source,sql]
----
ST_GeomAsGML(geom)
----

geom is a geometry. Return value is a clob with the GML2 value.

=== ST_AsEWKT

[source,sql]
----
ST_AsEWKT(geom)
----

geom is a geometry. Return value is a clob with the EWKT value. The EWKT value is the WKT value with the SRID prefix.

=== ST_AsKML

[source,sql]
----
ST_AsKML(geom)
----

geom is a geometry. Return value is a clob with the KML value. The KML value is effectively a simplified GML value and projected into SRID 4326.

== Relationship Functions

=== ST_CONTAINS

Returns true if geom1 contains geom2 contains another.

[source,sql]
----
ST_CONTAINS(geom1, geom2)
----

geom1, geom2 are geometries. Return value is a boolean.

=== ST_CROSSES

Returns true if the geometries cross.

[source,sql]
----
ST_CROSSES(geom1, geom2)
----

geom1, geom2 are geometries. Return value is a boolean.

=== ST_DISJOINT

Returns true if the geometries are disjoint.

[source,sql]
----
ST_DISJOINT(geom1, geom2)
----

geom1, geom2 are geometries. Return value is a boolean.

=== ST_DISTANCE

Returns the distance between two geometries.

[source,sql]
----
ST_DISTANCE(geom1, geom2)
----

geom1, geom2 are geometries. Return value is a double.

=== ST_EQUALS

Returns true if the two geometries are spatially equal - the points and order may differ, but neither geometry lies outside of the other.

[source,sql]
----
ST_EQUALS(geom1, geom2)
----

geom1, geom2 are geometries. Return value is a boolean.

=== ST_INTERSECTS

Returns true if the geometries intersect.

[source,sql]
----
ST_INTERSECT(geom1, geom2)
----

geom1, geom2 are geometries. Return value is a boolean.

=== ST_OVERLAPS

Returns true if the geometries overlap.

[source,sql]
----
ST_OVERLAPS(geom1, geom2)
----

geom1, geom2 are geometries. Return value is a boolean.

=== ST_TOUCHES

Returns true if the geometries touch.

[source,sql]
----
ST_TOUCHES(geom1, geom2)
----

geom1, geom2 are geometries. Return value is a boolean.

== Misc. Functions

=== ST_SRID

Returns the SRID for the geometry.

[source,sql]
----
ST_SRID(geom)
----

geom is a geometry. Return value is an integer. A 0 value rather than null will be returned for an unknown SRID on a non-null geometry.

=== ST_SetSRID

Set the SRID for the given geometry.

[source,sql]
----
ST_SetSRID(geom, srid)
----

geom is a geometry. srid is an integer. Return value is a geometry. Only the SRID metadata of the geometry is modified.

=== ST_TRANSFORM

Transforms the geometry value from one coordinate system to another.

[source,sql]
----
ST_TRANSFORM(geom, srid)
----

geom is a geometry. srid is an integer. Return value is a geometry. The srid value and the srid of the geometry value must exist in the SPATIAL_REF_SYS view.

