
= Transaction Support

{{ book.productnameFull }} utilizes XA transactions for participating in global transactions and for demarcating its local and command scoped transactions. 

{% if book.targetWildfly %}
http://narayana.io/[Narayana] is used by {{ book.productnameFull }} as its transaction manager.
{% endif %}
{% if book.targetWildfly %}
http://narayana.io/[Narayana] is optionally used by {{ book.productnameFull }} as its transaction manager.  In single source, or scenarios utilizing only non-XA sources, then the Spring platform transaction manager may be used.
{% endif %}
See http://narayana.io/documentation/index.html[this documentation] for the advanced features provided by Narayana.

.*{{ book.productnameFull }} Transaction Scopes*
|===
|Scope |Description

|Command
|Treats the user command as if all source commands are executed within the scope of the same transaction. The link:AutoCommitTxn_Execution_Property.adoc[AutoCommitTxn] execution property controls the behavior of command level transactions.

|Local
|The transaction boundary is local defined by a single client session.

|Global
|{{ book.productnameFull }} participates in a global transaction as an XA Resource.
|===

The default transaction isolation level for {{ book.productnameFull }} is READ_COMMITTED.

