= Virtual Database Related Properties

== Properties DATABASE Level

* _domain-ddl_

* _schema-ddl_

* _cache-metadata_

Can be "true" or "false". defaults to "false" for -vdb.xml deployments otherwise "true". If "false", {{ book.productnameFull }} will obtain metadata once for every launch of the vdb. "true" will save a file containing the metadata into the PROFILE/data/teiid directory

* _query-timeout_ 

Sets the default query timeout in milliseconds for queries executed against this VDB. 0 indicates that the server default query timeout should be used. Defaults to 0. Will have no effect if the server default query timeout is set to a lesser value. Note that clients can still set their own timeouts that will be managed on the client side.

* _lib_ 

Set to a list of modules for the vdb classpath for user defined function loading. See also link:../dev/Support_for_User-Defined_Functions_Non-Pushdown.adoc[Support for User-Defined Functions (Non-Pushdown)].

* _security-domain_ 

Set to the security domain to use if a specific security domain is applicable to the VDB. Otherwise the security domain list from the transport will be used.

[source,xml]
----
   <property name="security-domain" value="custom-security" />
----

NOTE: An admin needs to configure a matching "custom-security" login module in standalone-teiid.xml configuration file before the VDB is deployed.

* _connection.XXX_ 

For use by the ODBC transport and OData to set default connection/execution properties. See link:../client-dev/Driver_Connection.adoc[Driver Connection] for all properties. Note these are set on the connection after it has been established.

[source,xml]
----
   <property name="connection.partialResultsMode" value="true" />
----

* _authentication-type_ 

Authentication type of configured security domain. Allowed values currently are (GSS, USERPASSWORD). The default is set on the transport (typically USERPASSWORD).

* _password-pattern_ 

Regular expression matched against the connecting user’s name that determines if USERPASSWORD authentication is used. _password-pattern_ Takes precedence of over _authentication-type_. The default is _authentication-type_.

* _gss-pattern_ 

Regular expression matched against the connecting user’s name that determines if GSS authentication is used. _gss-pattern_ Takes precedence of over _password-pattern_. The default is _password-pattern_.

* _max-sessions-per-user_ (11.2+)

Maximum number of sessions allowed for each user, as identified by the user name, of this vdb.  No setting or a negative number indicates no per user max, but the session service max will still apply.  This is enforced at each {{ book.productnameFull }} server member in a cluster, and not cluster wide.  Derived sessions, created for tasks under an existing session, do not count against this maximum.

* _model.visible_ 

Used to override the visibility of imported vdb models, where model is the name of the imported model.

* _include-pg-metadata_ 

By default, PG metadata is always added to VDB unless link:../admin/System_Properties.adoc[System Properties] set property _org.teiid.addPGMetadata_ to false. This property enables adding PG metadata per VDB. Please note that if you are using ODBC to access your VDB, the VDB must include PG metadata.

* _lazy-invalidate_ 

By default TTL expiration will be invalidating - see link:../caching/Internal_Materialization.adoc[Internal Materialization]. Setting lazy-invalidate to true will make ttl refreshes non-invalidating.

* _deployment-name_ 

Effectively reserved. Will be set at deploy time by the server to the name of the server deployment.

== Properties Schema/Model Level
* _visible_

Marks the Schema is visible when value is _true_. visible falg is set to _false_, the Schema's metadata is hidden from any metadata requests. However note that this does not prohibit the user from issuing the queries against this Schema, in order to control the queries look into Data Roles.

* _multisource_

Marks the Schema as multi-source mode, where the data exists in partitions in multiple different sources. It is assumed that metadata of the Schema across all the data sources is exactly same.

* _multisource.columnName_

In a multi-source schema all the tables will be implicitly added with additional column to designate the partition column about identity of that source. This property defines the name of that column, the type will be always 'String'.

* _multisource.addColumn_

This flag to indicate, to add the implicit partition column to all the tables in this Schema. _true_ value adds the column. Default is _false_.

* _allowed-languages_

The allowed-languages property enables the languages use for any purpose in the vdb, while the allow-language permission allows the language to be used by users with RoleA. 