
= VDB Definition

A VDB or virtual database definition is contained in an XML file. For .vdb archive files created in the design tool, this file is embedded in the archive and most fields can be updated through tooling. The XML schema for this file can be found in the docs/teiid/schema directory.

[source,xml]
.*Example VDB XML*
----
<vdb name="${vdb-name}" version="${vdb-version}">
    
    <!-- Optional description -->
    <description>...</description>
    
    <!-- Optional connection-type -->
    <connection-type>...</connection-type>

    <!-- VDB properties -->
    <property name="${property-name}" value="${property-value}" />

    <!-- UDF defined in an AS module,  see Developers Guide --> 
    <property name ="lib" value ="{module-name}"></property>

    <import-vdb name="..." version="..." import-data-policies="true|false"/>

    <!-- define a model fragment for each data source -->
    <model visible="true" name="${model-name}" type="${model-type}" >

        <property name="..." value="..." />

        <source name="${source-name}" translator-name="${translator-name}" connection-jndi-name="${deployed-jndi-name}">

        <metadata type="${repository-type}">raw text</metadata>
        
        <!-- additional metadata
        <metadata type="${repository-type}">raw text</metadata>
        -->

    </model>

   <!-- define a model with multiple sources - see Multi-Source Models -->
   <model name="${model-name}" path="/Test/Customers.xmi">
        <property name="multisource" value="true"/>
        . . .
        <source name="${source-name}"
            translator-name="${translator-name}" connection-jndi-name="${deployed-jndi-name}"/>
        <source . . . />
        <source . . . />
    </model>

    <!-- see Reference Guide - Data Roles -->
    <data-role name="${role-name}">
        <description>${role-description}</description>
        ….
    </data-role>

    <!-- create translator instances that override default properties -->
    <translator name="${translator-name}" type="${translator-type}" />

        <property name="..." value="..." />

    </translator>
</vdb>
----

NOTE: *Property Substitution* - If a -vdb.xml file has defined property values like $\{my.property.name.value}, these can be replaced by actual values that are defined through JAVA system properties. To define system properties on a {{ book.asName }} server, please consult {{ book.asName }} documentation.

WARNING: You may choose to locally name vdb artifacts as you wish, but the runtime names of deployed VDB artifacts must either be *.vdb for a zip file or *-vdb.xml for an xml file. Failure to name the deployment properly will result in a deployment failure as the Teiid subsystem will not know how to properly handle the artifact.

== VDB Element

*Attributes*

* _name_ 

The name of the VDB. The VDB name referenced through the driver or datasource during the connection time.

* _version_ 

The version of the VDB. Provides an explicit versioning mechanism to the VDB name - see link:../admin/VDB_Versioning.adoc[VDB Versioning].

*Description Element*

Optional text element to describe the VDB.

*Connection Type Element*

Determines how clients can connect to the VDB.  Can be one of BY_VERSION, ANY, or NONE.  Defaults to BY_VERSION.  See link:../admin/VDB_Versioning.adoc[VDB Versioning].

*Property Elements*

* _cache-metadata_

Can be "true" or "false". defaults to "false" for -vdb.xml deployments otherwise "true". If "false", Teiid will obtain metadata once for every launch of the vdb. "true" will save a file containing the metadata into the PROFILE/data/teiid directory

* _query-timeout_ 

Sets the default query timeout in milliseconds for queries executed against this VDB. 0 indicates that the server default query timeout should be used. Defaults to 0. Will have no effect if the server default query timeout is set to a lesser value. Note that clients can still set their own timeouts that will be managed on the client side.

* _lib_ 

Set to a list of modules for the vdb classpath for user defined function loading. See also link:../dev/Support_for_User-Defined_Functions_Non-Pushdown.adoc[Support for User-Defined Functions (Non-Pushdown)].

* _security-domain_ 

Set to the security domain to use if a specific security domain is applicable to the VDB. Otherwise the security domain list from the transport will be used.

[source,xml]
----
   <property name="security-domain" value="custom-security" />
----

NOTE: An admin needs to configure a matching "custom-security" login module in standalone-teiid.xml configuration file before the VDB is deployed.

* _connection.XXX_ 

For use by the ODBC transport and OData to set default connection/execution properties. See link:../client-dev/Driver_Connection.adoc[Driver Connection] for all properties. Note these are set on the connection after it has been established.


[source,xml]
----
   <property name="connection.partialResultsMode" value="true" />
----

* _authentication-type_ 

Authentication type of configured security domain. Allowed values currently are (GSS, USERPASSWORD). The default is set on the transport (typically USERPASSWORD).

* _password-pattern_ 

Regular expression matched against the connecting user’s name that determines if USERPASSWORD authentication is used. _password-pattern_ Takes precedence of over _authentication-type_. The default is _authentication-type_.

* _gss-pattern_ 

Regular expression matched against the connecting user’s name that determines if GSS authentication is used. _gss-pattern_ Takes precedence of over _password-pattern_. The default is _password-pattern_.

* _model.visible_ 

Used to override the visibility of imported vdb models, where model is the name of the imported model.

* _include-pg-metadata_ 

By default, PG metadata is always added to VDB unless link:../admin/System_Properties.adoc[System Properties] set property _org.teiid.addPGMetadata_ to false. This property enables adding PG metadata per VDB. Please note that if you are using ODBC to access your VDB, the VDB must include PG metadata.

* _lazy-invalidate_ 

By default TTL expiration will be invalidating - see link:../caching/Internal_Materialization.adoc[Internal Materialization]. Setting lazy-invalidate to true will make ttl refreshes non-invalidating.

* _deployment-name_ 

Effectively reserved. Will be set at deploy time by the server to the name of the server deployment.

== import-vdb Element

*Attributes*

* _name_ 

The name of the VDB to be imported.

* _version_ 

The version of the VDB to be imported (should be an positive integer).

* _import-data-policies_ 

Optional attribute to indicate whether the data policies should be imported as well. Defaults to "true".

== Model Element

*Attributes*

* _name_ 

The name of the model is used as a top level schema name for all of the metadata imported from the connector. The name should be unique among all Models in the VDB and should not contain the '.' character.

* _visible_ 

By default this value is set to "true", when the value is set to "false", this model will not be visible to when JDBC metadata queries. Usually it is used to hide a model from client applications that should not directly issue queries against it. However, this does not prohibit either client application or other view models using this model, if they knew the schema for this model.

*Property Elements*

All properties are available as extension metadata on the corresponding `Schema` object that is accessible via the metadata API.

* _cache-metadata_ 

Can be "true" or "false". defaults to "false" for -vdb.xml deployments otherwise "true". If "false", Teiid will obtain metadata once for every launch of the vdb. "true" will save a file containing the metadata into the PROFILE/data/teiid directory Can be used to override the vdb level cache-metadata property.

* _teiid_rel:DETERMINISM_ 

Can be one of: 
DETERMINISM 
NONDETERMINISTIC 
COMMAND_DETERMINISTIC 
SESSION_DETERMINISTIC 
USER_DETERMINISTIC 
VDB_DETERMINISTIC 
DETERMINISTIC

Will influence the cache scope for result set cache entries formed from accessing this model. Alternatively the scope may be influenced through the Translator API or via table/procedure extension metadata.

*Source Element*

A source is a named binding of a translator and connection source to a model.

* _name_ 

The name of the source to use for this model. This can be any name you like, but will typically be the same as the model name. Having a name different than the model name is only useful in multi-source scenarios. In multi-source, the source names under a given model must be unique. If you have the same source bound to multiple models it may have the same name for each. An exception will be raised if the same source name is used for different sources.

* _translator-name_

The name or type of the Teiid Translator to use. Possible values include the built-in types (ws, file, ldap, oracle, sqlserver, db2, derby, etc.) and translators defined in the translators section.

* _connection-jndi-name_ 

The JNDI name of this source’s connection factory. There should be a corresponding "-ds.xml" file that defines the connection factory in the JBoss AS. Check out the deploying VDB dependencies section for info. You also need to deploy these connection factories before you can deploy the VDB.

*Property Elements*

* _importer.<propertyname>_ 

Property to be used by the connector importer for the model for purposes importing metadata. See possible property name/values in the Translator specific section. Note that using these properties you can narrow or widen the data elements available for integration.

*Metadata Element*

The optional metadata element defines the metadata repository type and optional raw metadata to be consumed by the metadata repository.

* _type_ 

The metadata repository type. Defaults to INDEX for Designer VDBs and NATIVE for non-Designer VDB source models. For all other deployments/models a value must be specified. Built-in types include DDL, NATIVE, INDEX, and DDL-FILE. The usage of the raw text varies with the by type. NATIVE and INDEX (only for Designer VDBs) metadata repositories do not use the raw text. The raw text for DDL is expected to be be a series of DDL statements that define the schema - see also link:DDL_Metadata.adoc[DDL Metadata]. DDL-FILE (used only with zip deployments) is similar to DDL, except that the raw text specifies an absolute path relative to the vdb root of the location of a file containing the DDL. See also link:../dev/Custom_Metadata_Repository.adoc[Custom Metadata Repository]. Use more than 1 metadata element to define multiple sources of metadata.

== Translator Element

*Attributes*

* _name_ 

The name of the the Translator. Referenced by the source element.

* _type_ 

The base type of the Translator. Can be one of the built-in types (ws, file, ldap, oracle, sqlserver, db2, derby, etc.).

*Property Elements*

* Set a value that overrides a translator default property. See possible property name/values in the Translator specific section.

