
= AdminShell

The AdminShell tooling provides scripting based programming environments that enable user to access, monitor and control a Teiid Server. Both the command line and graphical console tools are built on functionality provide by the Groovy ( http://groovy.codehaus.org/[http://groovy.codehaus.org/] ) project. The AdminShell tools can be used in ad-hoc scripting mode or to run pre-defined scripts.

AdminShell features:

1.  fully functional programming environment with resource flow control and exception management. See http://groovy.codehaus.org/[Groovy] docs for the full power of the language.
2.  quick administrative tool. The user can connect to a running Teiid Server and invoke any of the AdminAPI methods, such as "deploy" or "createDataSource", to control the Teiid System. Since this can be script driven, these tasks can be automated and re-run at a later time.
3.  simplified data access tool. The user can connect to a VDB, issue any SQL commands, and view the results of the query via http://groovy.codehaus.org/Database+features[Groovy Sql] extensions.
4.  migration tool. This can be used to develop scripts like moving the Virtual Databases (VDB), Connection Factories, and Configuration from one development environment to another. This will enable users to test
and automate their migration scripts before production deployments.
5.  testing tool. The JUnit ( http://junit.org/[http://junit.org] ) test framework is built in, see http://groovy.codehaus.org/Unit+Testing[Groovy Unit Tests]. User can write regression tests for checking system health, or data integrity that can be used to validate a system functionality automatically instead of manual verification by QA personnel.

== Download

AdminShell is distributed along with other Teiid downloads under "teiid-\{version}-adminshell-dist.zip" name. Download and unzip this file to any directory. Once you have unzipped the file, in root directory you will find "adminshell" and "adminshell-console" executable scripts to launch the command line and graphical tools respectively.

*Windows:* Double click or execute "adminshell.cmd"

*nix:* Execute the "adminshell.sh" script

