
= Clustering in Teiid

Since Teiid is installed in WildFly, there is no additional configuration needed beyond what was performed when Teiid is setup in Domain Mode. See the Domain Mode section in the Teiid link:Installation_Guide.adoc[Installation Guide]. Just make sure that you installed Teiid in every WildFly node and started all WildFly instances in the Domain mode that to be a part of the cluster.

Typically users create clusters to improve the performance of the system through:

* *Load Balancing*: Take look at the link:../client-dev/Client_Developers_Guide.adoc[Client Developer’s Guide] on how to use load balancing between multiple nodes.
* *Fail Over*: Take look at the link:../client-dev/Client_Developers_Guide.adoc[Client Developer’s Guide] on how to use fail over between multiple nodes.
* *Distributed Caching*: This is automatically done for you once you configure it as specified above. 
* *Event distribution*: metadata and data modifications will be distributed to all cluster members.

In the _Domain_ mode, the only way a user can deploy any artifacts is using either CLI or using the Admin API or Admin Shell. Copying VDB directly into the "deployments" directory is not supported.

