
= HDFS Data Sources

HDFS data sources use a built-in {{ book.productnameFull }} specific JCA connector. There are many ways to create the HDFS data source, using CLI, admin-console, etc. The example shown below uses the CLI tool, as this works in both Standalone and Domain modes.

Execute following command using the {{ book.asDocRoot }}Admin_Guide.html#running-the-cli[CLI] once you connected to the Server. Make sure you provide the correct directory name and other properties below. Add any additional properties required by the connector by duplicating the "connection-definitions" command below. Edit the JNDI name to match the JNDI name you used in VDB.

[source,java]
----
/subsystem=resource-adapters/resource-adapter=hdfs:add(module=org.jboss.teiid.resource-adapter.hdfs)
/subsystem=resource-adapters/resource-adapter=hdfs/connection-definitions=hdfsDS:add(jndi-name=${jndi.name}", class-name=org.teiid.resource.adapter.hdfs.HdfsManagedConnectionFactory, enabled=true, use-java-context=true)
/subsystem=resource-adapters/resource-adapter=hdfs/connection-definitions=hdfsDS/config-properties=FsUri:add(value="${fs.uri}")
/subsystem=resource-adapters/resource-adapter=hdfs:activate()
----

To find out all the properties that are supported by this Connector execute the following command in the CLI.

[source,java]
----
/subsystem=teiid:read-rar-description(rar-name=hdfs)
----

TIP: *Developer’s Tip* - If {{ book.asVersionNumber }} is running in standalone mode, you can also manually edit the  "<jboss-install>/standalone/configuration/standalone-teiid.xml" file and add the XML configuration defined in "<jboss-install>/docs/teiid/datasources/hdfs" directory under "resource-adapters" subsystem. Shutdown the server before you edit this file, and restart after the modifications are done.

