
= Infinispan Library Mode Data Sources

Infinispan Libary Mode data sources use a Teiid specific JCA connector that is deployed into {{ book.asVersionNumber }} during installation. This connector has the following options that
can be configured to access an Infinispan cache running in library mode:

*  Using JNDI
*  Using configuration file


== *Configuration*

=== *Pojo Jar*

The pojo class is the object that will be used to store the data in the cache.  It should be built accordingly:

*  To take advantage of the cache being indexed enabled, should annotate the class.  See [JDG documentation|https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Data_Grid/6.6/html-single/Infinispan_Query_Guide/index.html#chap-Annotating_Objects_and_Querying]
*  The class should be packaged into a jar so that it can be deployed as a module 


To configure the use of the pojo, do the following:

*  Deploy the pojo jar as a module in the jboss-as server.   Then define the "lib" property in the -vdb.xml and assign the correct module name.   This can be done using the following template:
[source,xml]
----
      <property name ="lib" value ="{pojo_module_name}"></property>
----

*  The JDG commons module, org.infinispan.commons, slot="jdg-6.x" or slot for version installed, needs to have the pojo dependency added:
[source,xml]
----
      <module name="{pojo_module_name}"   export="true" />
----
 
=== *Read and Write to the Cache*

The following are the required properties:

|===
|Property Name |Property Template|Description

| CacheTypeMap |cacheName:className[:pkFieldName[:cacheKeyJavaType]]  | For the indicated cache, map the root Java Object class name.  Optionally, but required for updates, identify which class attribute is the primary key to the cache.  The pkFieldName *MUST* match a corresponding getter/setter method in the pojo. Identify primary key java type when different than class attribute type 
|===

The following are the property options for defining how the CacheManager will be created/accessed:

[cols="2,2,5"]
|===
|Property Name 
|Req.
|Description

|module
|N
|Specify the {{ book.asName }} module that contains the cache classes that were defined in CacheTypeMap

|CacheJndiName
|N
|JNDI name to fine the CacheContainer

|ConfigurationFileNameForLocalCache
|N
|The Infinispan Configuration xml file for configuring a local cache
|===


=== *Using Cache for External Materialization*

The following are the additional properties that need to be configured if using the Remote Cache for external materialization:

|===
|Property Name |Req.|Description

| StagingCacheName | Y | Cache name for the staging cache used in materialization 
| AliasCacheName   | Y | Cache name for the alias cache used in tracking aliasing of the caches used in materialization 
|===

===  *Server Configuration*

There are many ways to create the data source; using CLI, link:AdminShell.adoc[AdminShell], admin-console etc. The example shown below uses the CLI tool, as this works in both Standalone and Domain modes.

Execute following command using {{ book.asDocRoot }}/Admin+Guide#AdminGuide-RunningtheCLI[CLI] once you connected to the Server. Make sure you provide the correct directory name and other properties below. Add any additional properties required by the connector by duplicating the "connection-definitions" command below. Edit the JNDI name to match the JNDI name you used in VDB.

[source,java]
----
batch
/subsystem=resource-adapters/resource-adapter=infinispan/connection-definitions=infinispanDS:add(jndi-name=java:/infinispanDS, class-name=org.teiid.resource.adapter.infinispan.libmode.InfinispanManagedConnectionFactory, enabled=true, use-java-context=true)
/subsystem=resource-adapters/resource-adapter=infinispan/connection-definitions=infinispanDS/config-properties=CacheTypeMap:add(value=trades:org.somewhere.Trade;tradeId)
/subsystem=resource-adapters/resource-adapter=infinispan/connection-definitions=infinispanDS/config-properties=Module:add(value=org.somewhere)
/subsystem=resource-adapters/resource-adapter=infinispan/connection-definitions=infinispanDS/config-properties=CacheJndiName:add(value=java:/myCache)
runbatch
----

To find out all the properties that are supported by this Infinispan Connector execute the following command in the CLI.

[source,java]
----
/subsystem=teiid:read-rar-description(rar-name=infinispan)
----

TIP: *Developer’s Tip* - If {{ book.asVersionNumber }} is running in standalone mode, you can also manually edit the "<jboss-install>/standalone/configuration/standalone-teiid.xml" file and add the XML configuration defined in *"<jboss-install>/docs/teiid/datasources/infinispan" directory under "resource-adapters" subsystem. Shutdown the server before you edit this file, and restart after the modifications are done.

NOTE: *Avoid Classloading Issues:* If you are using a servlet or other type of web application to create the DefaultCacheManager for the cache, be sure not to include the Infinispan jar dependencies in the application, but add their module dependencies.

