
= Migration Guide From Teiid 9.x

Teiid strives to maintain consistency between all versions, but when necessary breaking configuration and VDB/sql changes are made - and then typically only for major releases. 

You should consult the release notes for compatibility and configuration changes from each minor version that you are upgrading over.  This guide expands upon the release notes included in the kit to cover changes since 9.x.

If possible you should make your migration to Teiid 10 by first using Teiid 9.3.  Teiid 9.1 though 9.3 have the same JRE and WildFly requirements as Teiid 10.0.  See also link:Migration_Guide_From_Teiid_8.x.adoc[8 to 9 Migration Guide]

== Configuration Changes

Teiid Embedded by default will not allow the usage of the ENV function.  Use the EmbeddedConfiguration.setAllowEnvFunction to toggle this behavior.

== Compatibility Changes

The FROM_UNIXTIME function now matches the behavior of HIVE/IMPALA.  It accepts a long and returns a string, rather than a timestamp.

=== XML Document Model

The XML Document Model has been removed along with related client properties.  Please consider migrating to OData or utilizing SQL/XML functions for constructing documents.

== Kitting/Build Changes
