
= MongoDB Data Sources

MongoDB data sources use a Teiid specific JCA connector that is deployed into {{ book.asVersionNumber }} during installation. There are many ways to create a MongoDB data source, using CLI, link:AdminShell.adoc[AdminShell],
admin-console, etc. The example shown below uses the CLI tool, as this works in both Standalone and Domain modes.

Execute the following command using the {{ book.asDocRoot }}/Admin+Guide#AdminGuide-RunningtheCLI[CLI] once you connected to the Server. Make sure you provide the correct URL and user credentials. Add any additional properties required by the connector by duplicating the "connection-definitions" command below. Edit the JNDI name to match the JNDI name you used in VDB.

[source,java]
----
batch
/subsystem=resource-adapters/resource-adapter=mongodb/connection-definitions=mongodbDS:add(jndi-name="java:/mongoDS", class-name=org.teiid.resource.adapter.mongodb.MongoDBManagedConnectionFactory, enabled=true, use-java-context=true)
/subsystem=resource-adapters/resource-adapter=mongodb/connection-definitions=mongodbDS/config-properties=RemoteServerList:add(value="{host}:27017")
/subsystem=resource-adapters/resource-adapter=mongodb/connection-definitions=mongodbDS/config-properties=Database:add(value="{db-name}")
/subsystem=resource-adapters/resource-adapter=mongodb:activate
runbatch
----

All the properties that are defined on the RAR file are

|===
|Property Name |Description |Required |Default

|RemoteServerList
|A comma separated list of server locations. Each location can contain an optional port, of the format host:port
|
|

|Username
|Connection User’s Name
|false
|none

|Password
|Connection User’s password
|false
|none

|Database
|MongoDB database name
|true
|none
|===

To find out all the properties that are supported by this MongoDB Connector execute the following command in the CLI.

[source,java]
----
/subsystem=teiid:read-rar-description(rar-name=mongodb)
----

TIP: *Developer’s Tip* - If {{ book.asVersionNumber }} is running in standalone mode, you can also manually edit the "<jboss-install>/standalone/configuration/standalone-teiid.xml" file and add the XML configuration defined in *"<jboss-install>/docs/teiid/datasources/mongodb"* directory under "resource-adapters" subsystem. Shutdown the server before you edit this file, and restart after the modifications are done.

